### ISSUE TITLE
AttributeError: module 'gym.wrappers' has no attribute 'Monitor'

### ISSUE THREAD

**Issue by rayanehmi** [Replicable-MARL/MARLlib#101]
Got this error after installing MARLLib on a fresh conda environment 😥

The script I ran is the first example in README.md. I have also ran marllib/patch/add_patch.py before.

PS: It can be **fixed by manually downgrading gym** to <=0.21.0, but I'm not sure it doesn't break something else

**Comment by rayanehmi** [comment]
Relevant info : I installed marllib by cloning the repository and running `pip install -r requirements`

**Comment by Theohhhu** [comment]
Require gym==0.21.0. The version info was deleted from requirements in [commit 1366988](https://github.com/Replicable-MARL/MARLlib/commit/1366988bf63e10887de0eea4ca8c8e0c3a22edd9) as gym version introduced some error while building the docs. 
Sorry for the inconvenience.

**Comment by Theohhhu** [comment]
fixed [here](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/docs/source/handbook/installation.rst#marllib-installation).
