### ISSUE TITLE
[Solved] colab tutorial  error

### ISSUE THREAD

**Issue by daihuiao** [Replicable-MARL/MARLlib#108]
It seems that your tutorial on Colab has some problems in the installation of environmental installation. What is your python version. This is not an urgent problem, but it affects the learning of the beginner for the project。(*￣︶￣)

**Comment by daihuiao** [comment]
and i am confusied about your result in “/master/results/mpe_cooperative/simple_spread/mappo_gru_simple_spread)
/shared_policy_curve_file_0a23b.csv”. Why don't the reward value go up?I checked this result because your Demo used this algorithm and environment, but the reward in my training results went up and down,

**Comment by Theohhhu** [comment]
Hello, thank you for your attention.

MARLlib is currently undergoing active development, which means that the Colab environment may be unstable. We suggest that you clone the repository and perform the training/testing process on your local machine for more stability.

Regarding the results located at `/master/results/mpe_cooperative/simple_spread/mappo_gru_simple_spread`, it's important to note that these results are from an older version of MARLlib prior to the 1.0+ release. Some of the results may lack consistency and may not have been fine-tuned properly.

Therefore, we highly recommend reproducing all the results locally. For the simple_spread + MAPPO combination, we suggest using the following script:

```python
from marllib import marl
env = marl.make_env(environment_name="mpe", map_name="simple_spread", force_coop=True)
mappo = marl.algos.mappo(hyperparam_source="mpe")
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})
mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 10000000}, local_mode=False, num_gpus=1,
          num_workers=5, share_policy='all', checkpoint_freq=200)
```

The results will be stored in the same directory where you run the code.

**Comment by Theohhhu** [comment]
The colab has been updated. Feel free to explore it and give it a try by visiting [this link](https://colab.research.google.com/github/Replicable-MARL/MARLlib/blob/sy_dev/marllib.ipynb).

**Comment by DhananjayAshok** [comment]
```
Traceback (most recent call last):
  File "marllib_script.py", line 2, in <module>
    from marllib import marl
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/__init__.py", line 25, in <module>
    from marllib.marl.algos import run_il, run_vd, run_cc
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/__init__.py", line 23, in <module>
    from .run_cc import run_cc
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/run_cc.py", line 26, in <module>
    from marllib.marl.algos.scripts import POlICY_REGISTRY
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/scripts/__init__.py", line 23, in <module>
    from .vda2c import run_vda2c
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/scripts/vda2c.py", line 27, in <module>
    from marllib.marl.algos.core.VD.vda2c import VDA2CTrainer
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/core/__init__.py", line 23, in <module>
    from ray.rllib.agents.ppo.ppo_torch_policy import KLCoeffMixin
ModuleNotFoundError: No module named 'ray.rllib.agents'
```

I think this issue is still a problem
