### ISSUE TITLE
Example Policy is very poor

### ISSUE THREAD

**Issue by DhananjayAshok** [Replicable-MARL/MARLlib#113]
Hi there, I ran the example given in the ReadMe, and the model basically doesn't learn at all? At time step 0 the reward was -116.198 with episode_reward_max -69 and min -191.415, by the end of the training (313 iterations, ts 1001600) the reward min is less (-206.354, the reward max is only marginally higher -60.4847 and the reward is barely less -105.824. 

Is this an expected result? I am using the model exactly as provided in the ReadMe file.

**Comment by DhananjayAshok** [comment]
I also ran the configuration provided in another thread

`model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})`

This is also very bad with a reward that plateaus very early and does not improve after the first couple of steps. 

Is there a setting I can use on any env that will show good results?

**Comment by Theohhhu** [comment]
Hi,

We have made some revisions to the API usage script. The poor performance you experienced was primarily caused by the absence of force_coop=True. Please give it another try, and you should see that the final reward converges at around 60-70.
