### ISSUE TITLE
got some problem when rendering overcooked env! needing help, thx

### ISSUE THREAD

**Issue by wooooh1** [Replicable-MARL/MARLlib#115]

**Comment by Theohhhu** [comment]
Emm. Looks like the overcooked env has a tutorial on the game visualization on [Google Colab](https://colab.research.google.com/drive/1AAVP2P-QQhbx6WTOnIG54NXLXFbO7y6n#scrollTo=Z1RBlqADnTDw).

Have you tried that before?
