### ISSUE TITLE
Can I use MARLlib in my custom environment? 

### ISSUE THREAD

**Issue by Alilalily** [Replicable-MARL/MARLlib#121]
Hello there, I'm really impressed with the work that your project has accomplished so far. However, I noticed that it seems to only support the 15 environments that are currently mentioned in the readme and guide.  I'm interested in using your framework for my work and I'm wondering if it would be possible to implement support for additional or custom environments. Alternatively, would it be something that you plan to include in your future work?

**Comment by Theohhhu** [comment]
Thank you for your interest. One of the main features of MARLlib is its support for new environments. You can refer to the [example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/add_new_env.py) in the MARLlib repository, which demonstrates how to incorporate new environments into the library.
