### ISSUE TITLE
Older Version of MuJoCo

### ISSUE THREAD

**Issue by Squirrel-hub** [Replicable-MARL/MARLlib#127]
Could we have the latest version's of MuJoCo. For example Half_Cheetah_v3 since this one has different properties to the previous versions.

**Comment by Theohhhu** [comment]
We have recently updated MAMuJoCo to its latest version, which is now maintained under [Gymnasium-Robotics](https://github.com/Farama-Foundation/Gymnasium-Robotics).

To learn how to use it, you can refer to the examples provided at [Examples](https://marllib.readthedocs.io/en/latest/handbook/env.html#gymnasium-mamujoco).

Please note that Gymnasium-Robotics has not been merged into the master branch. You can access it by checking out the [rllib_1.8.0_dev](https://github.com/Replicable-MARL/MARLlib/tree/rllib_1.8.0_dev) branch.

If you encounter any bugs or issues, we encourage you to create a pull request (PR). We welcome contributions from the community.

**Comment by Theohhhu** [comment]
duplicated as #128
