### ISSUE TITLE
Waterworld gets stuck after certain timesteps 

### ISSUE THREAD

**Issue by prinshul** [Replicable-MARL/MARLlib#130]
While running waterworld environment from SISL, I get the following message and then the process hangs:

(raylet) [2023-06-19 01:48:23,965 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer
(raylet) [2023-06-19 01:48:23,965 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer
(raylet) [2023-06-19 01:48:23,965 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer
(raylet) [2023-06-19 01:48:24,173 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer
(raylet) [2023-06-19 01:48:24,207 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer
(raylet) [2023-06-19 01:48:24,207 E 1002285 1002285] worker.cc:199: Failed to send wait complete: IOError: 14: Connection reset by peer

Versions / Dependencies
ray==1.8.0
ray[tune]==1.8.0
ray[rllib]==1.8.0
icecream==2.1.3
torch==1.9.0
pettingzoo==1.12.0
pettingzoo[mpe]==1.12.0
supersuit==3.2.0
numpy==1.23.0
importlib-metadata==4.13.0
gym==0.21.0
PyYAML
python==3.8

#Reproduction script

from marllib import marl
import torch
torch.manual_seed(42)
env = marl.make_env(environment_name="sisl", map_name="waterworld", force_coop=True)

mappo = marl.algos.mappo(hyperparam_source="common")

model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 10000000}, local_mode=False, num_gpus=1,
num_workers=60, share_policy='group', checkpoint_freq=100)

I am facing this issue only in the Waterworld Sisl environment. I tried different parameters for mappo but still the issue persists. Is it because of older version v3? Or an issue in Ray?

**Comment by Theohhhu** [comment]
Could you please provide full trace of the error log? Thanks!

**Comment by Theohhhu** [comment]
Run 2 mil steps on my local machine without encountering any errors ;)

**Comment by prinshul** [comment]
I am able to run it for 1 million time steps on a different server.
