### ISSUE TITLE
Recording for SISL environments didn't work out-of-the-box

### ISSUE THREAD

**Issue by binakn** [Replicable-MARL/MARLlib#131]
Hey everyone, 

because I work on a remote machine without graphical interface I wanted to record the rendering of my SISL checkpoints as mp4 videos. It took some debugging to get it working, so I wanted to share the changes I had to make: 

Minimal example for the rendering with video recording: 
```python
# create environment
env = marl.make_env(environment_name="sisl", map_name="multiwalker", force_coop=True) 
env[0].metadata['render.modes'] = ["rgb_array"]  # needed to enable creation of video recorder processing rgb_arrays

# initialize algorithm and load hyperparameters
mappo = marl.algos.mappo(hyperparam_source='common') 

# build agent model based on env + algorithms + user preference if checked available
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

# rendering
mappo.render(env, model,
                restore_path={'params_path': "<root>/sisl_multiwalker/params.json", 
                            'model_path': "<root>/sisl_multiwalker/checkpoint-100"},  
                local_mode=True,
                share_policy="all",
                checkpoint_end=False,  
            )
```
To turn on the video in the config, I changed the render configuration within `restore_config_update()` in `/MARLlib/marllib/marl/algos/run_cc.py` as follows: 
```python
render_config = {
            "evaluation_interval": 1,
            "evaluation_num_episodes": 1, 
            "evaluation_num_workers": 1,
            "evaluation_config": {
                "record_env": "checkpoint_videos",  # was 'False' before
                "render_env": True,
            }
        }
```
In terms of fixes to make it work, I adjusted the rendering method in `MARLlib/marllib/envs/base_env/sisl.py` to be as follows: 

```python
    def render(self, mode=None):
        frame = self.env.render(mode=mode)
        time.sleep(0.05)
        return frame
```
Before this change, `env.render()` would return only `True` instead of the `rgb_array` frame that could be used for a video. 

Hope this helps & have a great day ! :smile:

**Comment by Theohhhu** [comment]
Thanks for sharing with us~

**Comment by fulacse** [comment]
I tried, but directory checkpoint_videos is empty
