### ISSUE TITLE
gfootball: Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)

### ISSUE THREAD

**Issue by xxdm** [Replicable-MARL/MARLlib#132]
Refer to the installation guide and run the example successfully. However, I am trying to set up the **gfootball** environment and encountered some issues: 
1.  I have install this successfully:
![image](https://github.com/Replicable-MARL/MARLlib/assets/10796263/922914f2-c47e-4370-b8b3-492103f18106)

2. 

> python3 -m pip install gfootball: 

-- The C compiler identification is GNU 11.3.0
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      **CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
      Call Stack (most recent call first):
        /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        CMakeLists.txt:40 (FIND_PACKAGE)**
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-2jyta7al/gfootball_4ebe1448ea5c46fa8ad2ed2e7de49dc1/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
      gfootball/build_game_engine.sh: line 29: pushd: third_party/gfootball_engine: No such file or directory
      error: Google Research Football compilation failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gfootball
  Running setup.py clean for gfootball
Failed to build gfootball

3. Regarding this issue, I have attempted the following methods:

> sudo apt-get install libgl1-mesa-dev

**Comment by Theohhhu** [comment]
The issue you're encountering appears to be related to `OpenGL`. It's a common problem on Linux, and you can search for a solution on Google. There are likely resources available such as [HARL](https://github.com/PKU-MARL/HARL) that you can refer to on how to install gfootball.

**Comment by xxdm** [comment]
Finally, this issue was not resolved, but when I switched to a different server, the problem did not occur.
