### ISSUE TITLE
fail to  pip gym==0.21.0

### ISSUE THREAD

**Issue by xxdm** [Replicable-MARL/MARLlib#133]
I can  pip install -r requirements.txt (in requirements.txt, gym==0.22.0)

![image](https://github.com/Replicable-MARL/MARLlib/assets/10796263/155a4107-428d-4d7b-be57-9630f64d6dfa)

Collecting gym==0.21.0
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Theohhhu** [comment]
There seems to be an issue with the gym library. You can check out the problem [here](https://github.com/openai/gym/issues/3176) to see if there is a possible fix for the bug. If not, you can consider using a different version of the gym library around `0.21.0`.

**Comment by xxdm** [comment]
I have solved the problem,  below is the version I have installed.
```python
ray==1.8.0
ray[tune]==1.8.0
ray[rllib]==1.8.0
icecream==2.1.3
torch==1.9.0
pettingzoo==1.12.0
pettingzoo[mpe]==1.12.0
supersuit==3.2.0
numpy==1.20.3
importlib-metadata==4.13.0
setuptools==65.5.0
gym==0.21.0
tensorboardx==2.2.0
protobuf==3.20
PyYAML
```

**Comment by Laurie2905-JOHN** [comment]
I had this error as well, but upgrading these packages fixed it.

pip install --upgrade pip setuptools wheel
