### ISSUE TITLE
Cannot locate tfevents files

### ISSUE THREAD

**Issue by Lauqz** [Replicable-MARL/MARLlib#136]
Hi everyone,

Thank you for developing this framework. It is incredibly useful.

Right now, I have successfully implemented an environment for my research. Anyway, I cannot find a way to visualize the learning curves using tensorboard.
Inside my project folder, I have another one called "exp_results", which contains "algo_enc_map" folders. Inside these, for each experiment, I have a pair of JSON files named "experiment_state-date" and "basic-variant-state-date" plus a trainer folder, again containing files such as "progress.csv", "result.json", "params.json", "params.pkl". Furthermore, there's a folder for each checkpoint done during training.

The problem is: no matter which logging directory I use for tensorboard, it will not find any dashboard since no tfevent files are present.

Could you please tell me what I am doing wrong? Thank you in advance.

**Comment by fortyMiles** [comment]
hello, in any script/<algo>.py file, there is a tune.run() function call. 

In this calling the last parameter named "local_dir" is the tf_logs dir. You can print it out or customize it if you want to know the specified path. 

Thanks.

**Comment by Lauqz** [comment]
@fortyMiles thank you very much. It seems I had installed the wrong tensorboard version; it successfully creates tfevents files with an older version (2.2). You could add this as a requirement.
