### ISSUE TITLE
Memory in each node increasing iteratively when training

### ISSUE THREAD

**Issue by aniri15** [Replicable-MARL/MARLlib#138]
I use maddpg to train the custom environment, but the memory used in each node increased iteratively and causes incomplete training after around 10 iterations.

== Status ==
Current time: 2023-07-02 12:20:01 (running for 00:28:35.94)
Memory usage on this node: 12.8/13.0 GiB: ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.
Using FIFO scheduling algorithm.
Resources requested: 4.0/4 CPUs, 0/0 GPUs, 0.0/6.06 GiB heap, 0.0/3.03 GiB objects
Result logdir: /home/anri/peg_in_hole_dev_aniri/exp_results/maddpg_mlp_default
Number of trials: 1/1 (1 RUNNING)
+---------------------------------------------------+----------+----------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+
| Trial name                                        | status   | loc                  |   iter |   total time (s) |    ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|---------------------------------------------------+----------+----------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------|
| MADDPGTrainer_TwoArmPegInHole_default_023f6_00000 | RUNNING  | 192.168.40.128:58357 |     12 |          1685.41 | 27024 |  211.045 |              335.006 |              133.397 |                250 |
+---------------------------------------------------+----------+----------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+

I also use maddpg to train in the example environment and got the same result. 
The traning code

from marllib import marl

env = marl.make_env(environment_name="mpe", map_name="simple_adversary", continuous_actions=True)

maddpg = marl.algos.maddpg(hyperparam_source='common')

model = marl.build_model(env, maddpg, {"core_arch": "mlp", "encode_layer": "128-256"})

maddpg.fit(env, model, stop={'episode_reward_mean': 10, 'timesteps_total': 20000000}, local_mode=True, num_gpus=0,
          num_workers=1, share_policy='individual', checkpoint_freq=100)

**Comment by fortyMiles** [comment]
hello, this is mechanism of Ray. Actually I also have met this problem. With the training, the memory usage will be increased linearly.

**Comment by aniri15** [comment]
> hello, this is mechanism of Ray. Actually I also have met this problem. With the training, the memory usage will be increased linearly.

Hello, thanks for your reply.
Yes, the memory used in each node increases the same amount iteratively.
I also found a interesting thing, if setting number of works larger, the increasing amount will be smaller, but I am not sure the reason, and is it possible to change ray init() to solve the problem?

**Comment by aniri15** [comment]
Hello,
Is it possible to resume the model from the last checkpoint and continue to train? I did not find the relative guide.
Thanks in advance.

**Comment by Theohhhu** [comment]
Yes. Loading and rendering on one environment can be seen as a specific scenario of resuming the model from the last checkpoint and continuing training.  We will add an example on general model loading very soon.
