### ISSUE TITLE
ray.exceptions.RayTaskError(RayOutOfMemoryError)

### ISSUE THREAD

**Issue by daihuiao** [Replicable-MARL/MARLlib#142]
I used the following code, but RayoutoFMemoryerror appeared,
```python
from marllib import marl

# prepare env
env = marl.make_env(environment_name="mpe", map_name="simple_spread", force_coop=True)

# initialize algorithm with appointed hyper-parameters
mappo = marl.algos.maddpg(hyperparam_source='mpe')

# build agent model based on env + algorithms + user preference
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

# start training
mappo.fit(env, model, stop={'timesteps_total': 1000000}, share_policy='group')
```

This program occupies 80 G memory：
PID	MEM	COMMAND
804539	83.9GiB	/home/ps/anaconda3/envs/sea_clone_clone/bin/python /home/ps/pycharm-2023.1.2/plugins/python/helpers/

Where is the problem?I just replaced the MAPPO of the sample code with MADDPG.

**Comment by Theohhhu** [comment]
This is a normal phenomenon in MARLlib, where each agent is treated as an individual entity, and as a result, each agent maintains its own buffer. This approach often leads to larger memory requirements, particularly for off-policy algorithms, to exchange for the flexibility in dealing with diverse task modes.

**Comment by daihuiao** [comment]
First of all, thank you very much for your reply. However, I don't think 80GB memory usage is a normal phenomenon. There are any parameters or methods that can fix the problem. O(∩_∩)O

**Comment by Theohhhu** [comment]
You can set a small `buffer_size_episode` in  such as [here](https://github.com/Replicable-MARL/MARLlib/blob/master/marllib/marl/algos/hyperparams/common/maddpg.yaml)
