### ISSUE TITLE
Can I set the parameter exp_info["evaluation_interval"] in run_il.py to be particularly large?

### ISSUE THREAD

**Issue by TD-Jia** [Replicable-MARL/MARLlib#145]
Hello! I'm really impressed with this work.I believe this will be an impactful contribution to the field of reinforcement learning.
Regarding this framework, I have a question to seek your advice.When I use this framework to run my env, I found that the evaluation process will reset my env. For example, exp_info["evaluation_interval"]=10, at the tenth iter, my env will be reset. In order to avoid this phenomenon, I set the parameter in run_il.py to exp_info["evaluation_interval"]=9999999. I find this makes sense. I would like to consult you whether such a setting will affect the training effect of the agent? That is, the evaluation process is not performed. I found that the evaluation process seems to only evaluate some results of the training process, and does not affect the training effect.
Thanks in advance for your reply！

**Comment by Theohhhu** [comment]
Hi, thank you for your kind words.

The training process will not be affected by the evaluation process, but the results obtained from the evaluation will be impacted. If you want to perform manual evaluations, you can set a large evaluation interval and load the model after training for a significant number of timesteps. You can refer to [this example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/load_model.py) for guidance on how to load the model for evaluation purposes.

**Comment by TD-Jia** [comment]
Thanks for your reply! I will try it.
