### ISSUE TITLE
Seeding: Getting Deterministic Results

### ISSUE THREAD

**Issue by SinergAIze** [Replicable-MARL/MARLlib#149]
Hi!

I have had the chance to study your work, and I’ve decided on MARLlib as our MARL framework of choice. Thanks for sharing your fantastic hard work!

While testing MARLlib, I couldn’t help but notice that the results that come out of `.fit()` are not deterministic. That is, even if the `seed: 321` is specified in the the `ray.yaml` config file, multiple runs of the same algorithm on the same environment will generate slightly differing results.

Being able to reliably obtain a deterministic result would allow any MARLlib user to better test, debug, replicate and confirm their implementations.

From what I could dig around I deduced that there are 2 main parts that need seeding: The environment and the model.

## Seeding the Environment.
From the tests I conducted, which were all based on the Cooperative MPE environments, I was able to figure out that while your custom `RLlibMPE` environment class does not have a way to set the seed, all the libraries below it do. Therefore, by simply calling

```python
env = marl.make_env(
    environment_name='mpe',
    map_name='simple_speaker_listener',
    force_coop=True
)

env[0].env.seed(seed=42)
```

I was able to test that any subsequent observations and rewards were the same across multiple executions. However, I am not sure this applies across all workers that might not execute this seed setting code. I am not sure how to ensure all workers seed their environments.

To make the API a little more friendly, I was wondering:
Why not also include a seeding method in `RLlibMPE`, or a way to specify the seed directly via for example: `marl.make_env(seed=...)`? Perhaps consider adding a `seed: ...` field in the environment `.yaml` config file as well?

## Seeding the model.
When it comes to the model side of things, I was not able to figure out how to ‘manually’ seed the model initialisation. I was able to determine that the seed argument both via the API (ie `.fit(..., seed=xxx)`) and via the `ray.yaml` config file is passed to `tune.run()`, and then it calls `update_global_seed_if_necessary()` to set all the seeds. I’ve checked that this function is being called, and it is, but it doesn’t seem to be making a difference. I wonder if this has to do with the multiple workers not executing this code as well.

I was wondering if there are plans on your end to address this seeding issue. I'm sure it would be greatly appreciated by the whole community. Thank you!

Cheers!

**Comment by Theohhhu** [comment]
Thank you for your attention on our work and all the information. 

To ensure deterministic results in MARLlib, you can add the line `self.env.seed(321)` at [this location](https://github.com/Replicable-MARL/MARLlib/blob/0ac275e6132e653f826b107e79963a1485bcd425/marllib/envs/base_env/mpe.py#L115)(works for other environments as well). This will fix the seed for the inner environment.

However, it's important to note that if you have different worker numbers set in two experiments, even with the same seed, the reported results in the tabular format can still differ. This discrepancy could potentially be an issue with Ray/RLlib, and it may require further investigation to determine the cause. 

As for the model side, when you set `seed 321` to `ray.tune`, all the algorithms side should be deterministic.

Theo

**Comment by SinergAIze** [comment]
Hello!

Great news: I was not able to re-create the issues I was having! 😅

Seeding seems to work as intended after appending `self.env.seed(...)` on line 116 at: https://github.com/Replicable-MARL/MARLlib/blob/0ac275e6132e653f826b107e79963a1485bcd425/marllib/envs/base_env/mpe.py#L95-L116

If I could make a small suggestion - why not pass the seed from the `ray.yaml` file to the above directly? That way the Ray seed will be all you need to set!

This can be done simply by adding a 'seed' argument to the `RLlibMPE.__init__(..., seed=321)`, and then initialising the env using `ENV_REGISTRY[env_config["env"]](env_config["env_args"], seed=env_config["seed"])` in `marllib.__init__()`, since the `ray.yaml` config is already merged with the `env_config`s.

Of course, don't forget to do the same for the `COOP_ENV_REGISTRY` envs too (and possibly all other envs? 😄)
