### ISSUE TITLE
How to use custom environment without adding them to the repo?

### ISSUE THREAD

**Issue by PaLeroy** [Replicable-MARL/MARLlib#150]
Hello!

I aim to execute MARLLib algorithms using my own MARL environment.

I am following the [add_new_env](https://github.com/Replicable-MARL/MARLlib/blob/rllib_1.8.0_dev/examples/add_new_env.py) example but also looking at how SMAC has been integrated into MARLLib.

I installed MARLLib through PyPI because I just want to have some files in my repo to demonstrate how to use MARLLib with our environment but it appears that the [`make_env`](https://github.com/Replicable-MARL/MARLlib/blob/0ac275e6132e653f826b107e79963a1485bcd425/marllib/marl/__init__.py#L72) function requires some config file accessible only by a hardcoded `env_config_file_path` included in the `make_env` function.

Did I miss something or is it infeasible for the moment?

I would not mind trying to help find a fix.

Cheers for your nice work putting up this repo.

**Comment by Theohhhu** [comment]
Temporarily, the configuration path is fixed and must be located within the project's inner path. I acknowledge that this approach is not elegant and will work on making it possible to set the configuration path externally.

**Comment by Theohhhu** [comment]
Please Check out [here](https://github.com/Replicable-MARL/MARLlib/blob/521316d95ed18f876ee7c4f54a51b5e2f7a73ef8/examples/add_new_env.py#L128). #153

**Comment by PaLeroy** [comment]
Thanks!
