### ISSUE TITLE
Questions about pid

### ISSUE THREAD

**Issue by wanglinghao1** [Replicable-MARL/MARLlib#152]
When I run the program, I find that every time a certain iteration passes, the program will only have one PID running. It is not until a longer period of time that this phenomenon disappears and there are multiple PIDs running at the same time

**Comment by fortyMiles** [comment]
Hello, as for the PID, my opinion is that the operating system will maintain only one single PID (processing) at a single time if you are running on a single machine. By some cycling algorithms, the OS will switch or spawn more processings after some tasks are finished.
