### ISSUE TITLE
Compatibility Issue with wandb

### ISSUE THREAD

**Issue by fyqqyf** [Replicable-MARL/MARLlib#154]
I am facing compatibility issues while using the MARLlib with wandb. I would like to understand how I can make these two work together seamlessly.

Thank you for your assistance in resolving this compatibility issue.

**Comment by fortyMiles** [comment]
hello, would you please post your issues, or bugs, on this place. It may help to find out the reason together.

**Comment by Theohhhu** [comment]
Closed as no response.
