### ISSUE TITLE
Question regarding upgrade to RLlib v2.x

### ISSUE THREAD

**Issue by janrope** [Replicable-MARL/MARLlib#155]
Hey,

do you plan to upgrade to Ray 2.x and RLlib 2.x in the near future or will this project stay on the 1.8 version?

There have been major changes in the Ray project structure but also big improvements regarding RLlib. Currently, I'm facing the problem that I need the algorithms implemented in your project but also capabilities of RLlib 2.x like multi-gpu and gymnasium support (2.3 and 2.5).

**Comment by Theohhhu** [comment]
We have observed that the Ray/RLlib main repository is currently undergoing active development, and its backward compatibility might not be as robust. Nevertheless, we strongly believe that an upgrade is necessary. In the near future, we will be releasing a detailed plan outlining the steps for the upgrade.
