### ISSUE TITLE
[Bug] Dockerfile - Base image comes with Python 3.7 and wrong gym version

### ISSUE THREAD

**Issue by janrope** [Replicable-MARL/MARLlib#158]
Hello,

the provided Dockerfile comes with the following base image: `FROM pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime`

**The problem**

However, this image comes with Python 3.7 and is incompatible with the current requirements of MARLlib - so
`RUN git clone https://github.com/Replicable-MARL/MARLlib.git
WORKDIR /workspace/MARLlib
RUN pip install -e .`
breaks due to incompatible Python versions.

Additionally, I get the error `marllib 1.0.3 requires gym==0.22.0, but you have gym 0.21.0 which is incompatible` due to the line `RUN pip install icecream && pip install lbforaging==1.0.15 && pip install supersuit && pip install gym==0.21.0 && pip install importlib-metadata==4.13.0`.

**Proposed solution**

A recent base image should be used. However, there are multiple pitfalls in upgrading. One example of a quite old base image that at least comes with Python 3.9 is: `pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime`. But for that, PyTorch and a couple of other libraries should be bumped to higher versions in the requirements.txt. Additionally, `python patch/add_patch.py -y` throws an error:

> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower). 

**Why is this important to me?**

I try to run everything in dev containers for simple portability. Even after a couple of hours, I have no fully working container with MARLlib due to incompatibility with dependencies, etc. Even one I've got running at some point seems to be caught in an endless loop once I call `from marllib import marl`.
Any help is highly appreciated. I would love to not only use this framework but also contribute to hopefully push some of the "antiquated" dependencies. But due to the problems I experienced so far I'm debating with myself if it is worth contributing here or to rather try to port algorithms from here to RLlib and contribute there.

**Comment by Ivan-Zhong** [comment]
Hello, we have updated the Dockerfile. Please give it a try. If you encounter any further issues, we'd be more than willing to help you.

**Comment by janrope** [comment]
Hey, thanks for the update. The Dockerfile now works for me.
I guess in the long run it would be nice if the install of marllib via pip would not lead to a lowered version reinstall of many packages. But that's a nice to have, not a necessity.
