### ISSUE TITLE
Can I customize Envrionment?

### ISSUE THREAD

**Issue by jkjk9450** [Replicable-MARL/MARLlib#159]
Hello, I want to use the MARLlib for my own problem, and I want to know how I can customize the Environment to use the MARLlib. Can I get some example for using custom environment? Maybe marl.make_env only can make the base_env.

**Comment by Theohhhu** [comment]
Here is an [example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/add_new_env.py) on how to add a new environment to MARLlib.

Any further concern is welcome.

**Comment by jkjk9450** [comment]
Thank you!
