### ISSUE TITLE
from marllib.marl.algos import run_il, run_vd, run_cc

### ISSUE THREAD

**Issue by shivarajabi** [Replicable-MARL/MARLlib#160]
i try to import marllib but this error ocured which is about ray, i install ray full version and rl version but i still have this error 

> [c:\Users\Asus\anaconda3\envs\marllib\lib\site-packages\marllib\marl\__init__.py:25](file:///C:/Users/Asus/anaconda3/envs/marllib/lib/site-packages/marllib/marl/__init__.py:25)
>       1 # MIT License
>       2 
>       3 # Copyright (c) 2023 Replicable-MARL
>    (...)
>      20 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
>      21 # SOFTWARE.
>      23 from marllib.marl.common import dict_update, get_model_config, check_algo_type, \
>      24     recursive_dict_update
> ---> 25 from marllib.marl.algos import run_il, run_vd, run_cc
> 

> File [c:\Users\Asus\anaconda3\envs\marllib\lib\site-packages\marllib\marl\algos\core\__init__.py:23](file:///C:/Users/Asus/anaconda3/envs/marllib/lib/site-packages/marllib/marl/algos/core/__init__.py:23)
>       1 # MIT License
>       2 
>       3 # Copyright (c) 2023 Replicable-MARL
>    (...)
>      20 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
>      21 # SOFTWARE.
> ---> 23 from ray.rllib.agents.ppo.ppo_torch_policy import KLCoeffMixin
>      24 import gym
>      25 from ray.rllib.policy.policy import Policy
> 
> ModuleNotFoundError: No module named 'ray.rllib.agents'

**Comment by Theohhhu** [comment]
Guess you installed the wrong version of Ray.

Make sure your version of Ray is 1.8.0 by running `pip install ray==1.8.0`.

Any question is welcome.

**Comment by shivarajabi** [comment]
thanks for responding i reinstall it to the version you suggested but i still get this kinds of errors:
`partially initialized module 'ray' has no attribute '_private' (most likely due to a circular import)`
when i import marllib

**Comment by Theohhhu** [comment]
Can you please share how you installed MARLlib and how you use it?

**Comment by shivarajabi** [comment]
https://github.com/Replicable-MARL/MARLlib 
i used this instruction step by step :(

**Comment by Theohhhu** [comment]
How you fixed the bug? Based on the information you've provided, I can't pinpoint the exact location of the bug.
