### ISSUE TITLE
DeepMind MuJoCo Multi-Agent Soccer Environment

### ISSUE THREAD

**Issue by wakaka821** [Replicable-MARL/MARLlib#163]
Dm_control provides many interesting reinforcement learning environments. Have contributors considered adding the DeepMind MuJoCo multi-agent soccer environment to MRALlib?
(https://github.com/deepmind/dm_control/tree/main/dm_control/locomotion/soccer)

**Comment by Theohhhu** [comment]
Hi, we embrace all contributions from the open-source community. If you're interested in incorporating a new environment into MARLlib, you can refer to the guidelines provided [here](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/add_new_env.py). We encourage and appreciate any pull requests that come our way.
