### ISSUE TITLE
How to load and restart the training from the saved checkpoint?

### ISSUE THREAD

**Issue by jkjk9450** [Replicable-MARL/MARLlib#164]
Hello, I trained my model and saved the checkpoints.
But, my model is not trained enough and I want to restart the training from the last checkpoint.
How can I load the model from the checkpoint?

**Comment by Theohhhu** [comment]
Hi, here is an [example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/load_model.py) for you to refer.

Feel free to ask any other questions you may have.

**Comment by jkjk9450** [comment]
> Hi, here is an [example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/load_model.py) for you to refer.
> 
> Feel free to ask any other questions you may have.

Thank you for your answer, and I have one more question. Can I save the best model (which means the model that shows the best mean episode reward for iteration)? The checkpoint_freq only can save the model with the constant frequency.

**Comment by jkjk9450** [comment]
> Sorry, I can not provide a direct solution for finding and loading the best model, but a similar functionality can be found in [RLlib's example](https://github.com/ray-project/ray/blob/72fdf3be605e4aadfd9a8c3f01dd7843c01cb8fd/rllib/examples/checkpoint_by_custom_criteria.py#L71). The results of `ray.tune` in MARLlib can be found [here](https://github.com/Replicable-MARL/MARLlib/blob/eb3d26a453a1c14dfbf1ef399909de3c4dab1f3f/marllib/marl/algos/run_cc.py#L194) (also in `run_vd` and `run_il`). Combine the two will solve your problem hopefully.

Thank you for your help!!

**Comment by Theohhhu** [comment]
If you have any more questions or need further assistance feel free to reopen the conversation.
