### ISSUE TITLE
[Question] Test pipeline runtime

### ISSUE THREAD

**Issue by janrope** [Replicable-MARL/MARLlib#166]
Hey, how long do the tests usually run? 
I started them about 2 hours ago and they are still running. I'm just wondering if it's due to my Docker setup. What runtimes are you experiencing when you run the tests?

**Comment by Theohhhu** [comment]
Hi, thank you for your interest in MARLlib.

On my local server, the testing duration will vary depending on the number of test units I run. It's important to mention that certain parts of the test file require additional environments to be installed, like SMAC, to successfully pass the test.

**Comment by janrope** [comment]
So is it normal that just testing the algorithms can take more than 2 hours? For me, it's really just about understanding if my Docker setup is working as expected in its current form or if Docker is causing a problem.

I would like to use MARLlib as a basis for my research and develop it further. However, I work on Windows systems and decided to go with Docker-based solutions some time ago because I was having issues with Ray on Windows as well. Since WSL2, Docker can pass through the GPU, and with VSCode dev-container integration, development in Docker itself is extremely simplified.
