### ISSUE TITLE
[Enhancement] Development Container (devcontainer)

### ISSUE THREAD

**Issue by janrope** [Replicable-MARL/MARLlib#167]
Hey,

I just started with MARLlib and I like the project a lot. However, it was a quite painful experience for me to not only get it to run on my Windows machine (with the updated Dockerfile) but to also have an editable/developing version.

I know that Windows/Mac support is on the Roadmap and I think that's a good move (even though I personally would prioritize dependency upgrades more). Anyway, you can already now have full functionality/support on your Windows/Mac system with the help of Docker and the magic of a development container (devcontainer).

**What are devcontainers?**
Development containers are specifically designed containers for developers, basically emulating a nice virtual machine with a magic setup. A general overview, including supporting tools like IDEs (VSCode, etc.) can be found here at [containers.dev](https://containers.dev/). Github also has a nice introduction in their [github docs](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers).

**Why devcontainer?**
As I already mentioned, this way you can work on any platform. Moreover, if anything breaks (dependencies or similar) that I can't easily fix, I simply rebuild the container and everything works again. Bonus, I can add any code, have editable library versions, control resources, simplify collaboration, and more. Finally, integration with VSCode (my preferred IDE) is seamless and as easy as it gets.

**My proposal**
I created a devcontainer setup for the MARLlib project. With the extra `.devcontainer` folder, if someone clones this project and uses a supporting IDE, the IDE will directly ask if this project should run in a devcontainer that certainly comes with a compatible system+dependencies.

I will create a pull request soon and link it here for discussion. Please let me know if you've got questions or concerns.

**Comment by Ivan-Zhong** [comment]
Thanks for your contribution. Pull request #168 has been merged.
