### ISSUE TITLE
MAPPOTrainer' object has no attribute '_local_ip

### ISSUE THREAD

**Issue by allenjeffreywu** [Replicable-MARL/MARLlib#174]
Creating a new environment for CityLearn with two buildings and following the add_new_env file.
I can run the add_new_env.py file without issue, but my CityLearn implementation (which is similar) cannot run.

Ran into this issue with RAY.
`MAPPOTrainer.get_auto_filled_metrics()::Exiting[39m (pid=13027, ip=10.0.0.8, repr=MAPPOTrainer)
  File "/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip'`

my current pip list:

`
Package                       Version
----------------------------- ----------
aiosignal                     1.3.1
asttokens                     2.2.1
async-timeout                 4.0.2
attrs                         23.1.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
brotlipy                      0.7.0
certifi                       2023.5.7
cffi                          1.15.1
chardet                       5.1.0
charset-normalizer            3.1.0
CityLearn                     1.8.0
click                         8.1.3
cloudpickle                   2.0.0
cmake                         3.26.4
colorama                      0.4.6
contourpy                     1.1.0
cryptography                  39.0.1
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
dm-tree                       0.1.8
entrypoints                   0.4
executing                     1.2.0
Farama-Notifications          0.0.4
filelock                      3.12.2
fonttools                     4.40.0
frozenlist                    1.4.0
gmpy2                         2.1.2
grpcio                        1.51.3
gym                           0.20.0
gym-notices                   0.0.8
gymnasium                     0.29.0
icecream                      2.1.3
idna                          3.4
imageio                       2.31.1
importlib-metadata            4.13.0
importlib-resources           5.12.0
ipykernel                     6.15.0
ipython                       8.12.0
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.3.1
jsonschema                    4.17.3
jupyter-client                7.0.6
jupyter_core                  4.12.0
kiwisolver                    1.4.4
lit                           16.0.6
lz4                           4.3.2
ma-gym                        0.0.14
MarkupSafe                    2.1.3
marllib                       1.0.3
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mkl-fft                       1.3.6
mkl-random                    1.2.2
mkl-service                   2.4.0
mpmath                        1.3.0
msgpack                       1.0.5
nest-asyncio                  1.5.6
networkx                      3.1
numpy                         1.20.3
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
opencv-python                 3.4.18.65
packaging                     23.1
pandas                        2.0.3
parso                         0.8.3
PettingZoo                    1.12.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.0.0
pip                           23.0.1
pkgutil_resolve_name          1.3.10
prompt-toolkit                3.0.39
protobuf                      3.20.3
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
pyglet                        1.5.27
Pygments                      2.15.1
pyOpenSSL                     23.0.0
pyparsing                     3.1.0
pyrsistent                    0.19.3
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3
PyWavelets                    1.4.1
PyYAML                        6.0
pyzmq                         19.0.2
ray                           1.8.0
redis                         4.6.0
requests                      2.31.0
scikit-image                  0.19.3
scikit-learn                  1.0.2
scipy                         1.10.1
setuptools                    67.8.0
simplejson                    3.19.1
six                           1.16.0
stack-data                    0.6.2
SuperSuit                     3.2.0
sympy                         1.12
tabulate                      0.9.0
tensorboardX                  2.6.1
threadpoolctl                 3.1.0
tifffile                      2023.7.4
torch                         1.9.0
torchaudio                    2.0.2
torchvision                   0.15.2
tornado                       6.1
traitlets                     5.9.0
triton                        2.0.0
typing_extensions             4.7.1
tzdata                        2023.3
urllib3                       2.0.3
wcwidth                       0.2.6
wheel                         0.38.4
zipp                          3.15.0
`

This was done in Ubuntu 22.04.2 LTS

What can I do in my implementation to solve this error?

**Comment by Theohhhu** [comment]
Can you pls show me the full log of error for tracing the bug?

**Comment by allenjeffreywu** [comment]
AttributeError: 'RolloutWorker' object has no attribute 'policy_map' at
time: 1.69164e+09
2023-08-09 20:58:18,309 ERROR actor.py:746 -- Exception raised in creation
task: The actor died because of an error raised in its creation task,
ray::MAPPOTrainer.__init__() (pid=1020, ip=10.0.0.8)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py",
line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py",
line 623, in __init__
    super().__init__(config, logger_creator)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py",
line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py",
line 147, in setup
    super().setup(config)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py",
line 776, in setup
    self._init(self.config, self.env_creator)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py",
line 171, in _init
    self.workers = self._make_workers(
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py",
line 858, in _make_workers
    return WorkerSet(
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py",
line 87, in __init__
    remote_spaces = ray.get(self.remote_workers(
ray.exceptions.RayTaskError(AttributeError):
ray::RolloutWorker.foreach_policy()::Exiting (pid=1020, ip=10.0.0.8,
repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class
object at 0x7f968056a970>)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py",
line 1206, in foreach_policy
    for pid, policy in self.policy_map.items()
AttributeError: 'RolloutWorker' object has no attribute 'policy_map'
[2023-08-09 20:58:18,311 E 1020 1020] core_worker.cc:1561: Pushed Error
with JobID: 01000000 of type: task with message:
ray::MAPPOTrainer.get_auto_filled_metrics()::Exiting (pid=1020,
ip=10.0.0.8, repr=MAPPOTrainer)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py",
line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip' at time:
1.69164e+09
[2023-08-09 20:58:18,813 E 1020 1020] core_worker.cc:1561: Pushed Error
with JobID: 01000000 of type: task with message:
ray::MAPPOTrainer.train()::Exiting (pid=1020, ip=10.0.0.8,
repr=MAPPOTrainer)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py",
line 682, in train
    raise e
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py",
line 668, in train
    result = Trainable.train(self)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py",
line 283, in train
    result = self.step()
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py",
line 206, in step
    step_results = next(self.train_exec_impl)
AttributeError: 'MAPPOTrainer' object has no attribute 'train_exec_impl' at
time: 1.69164e+09
Traceback (most recent call last):
  File "/home/allenwu/anaconda3/envs/marllib/lib/python3.8/runpy.py", line
194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/allenwu/anaconda3/envs/marllib/lib/python3.8/runpy.py", line
87, in _run_code
    exec(code, run_globals)
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py",
line 39, in <module>
    cli.main()
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py",
line 430, in main
    run()
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py",
line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py",
line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py",
line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File
"/home/allenwu/.var/app/com.visualstudio.code/data/vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py",
line 124, in _run_code
    exec(code, run_globals)
  File "/home/allenwu/Desktop/work/MARLlib-1.0.3/add_citylearn_env.py",
line 123, in <module>
    mappo.fit(env, model, stop={'episode_reward_mean': 2000,
'timesteps_total': 10000000}, local_mode=True, num_gpus=1,
  File "/home/allenwu/Desktop/work/MARLlib-1.0.3/marllib/marl/__init__.py",
line 313, in fit
    run_cc(self.config_dict, env_instance, model_class, stop=stop)
  File
"/home/allenwu/Desktop/work/MARLlib-1.0.3/marllib/marl/algos/run_cc.py",
line 166, in run_cc
    results = POlICY_REGISTRY[exp_info["algorithm"]](model, exp_info,
run_config, env_info, stop_config,
  File
"/home/allenwu/Desktop/work/MARLlib-1.0.3/marllib/marl/algos/scripts/mappo.py",
line 119, in run_mappo
    results = tune.run(MAPPOTrainer,
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py",
line 603, in run
    _report_progress(runner, progress_reporter)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py",
line 68, in _report_progress
    reporter.report(trials, done, sched_debug_str, executor_debug_str)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py",
line 520, in report
    print(self._progress_str(trials, done, *sys_info))
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py",
line 279, in _progress_str
    user_metrics = self._infer_user_metrics(trials, self._infer_limit)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py",
line 325, in _infer_user_metrics
    if not t.last_result:
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial.py",
line 433, in last_result
    self._get_default_result_or_future()
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial.py",
line 409, in _get_default_result_or_future
    self._default_result_or_future = ray.get(
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py",
line 105, in wrapper
    return func(*args, **kwargs)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/worker.py",
line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError):
ray::MAPPOTrainer.get_auto_filled_metrics()::Exiting (pid=1020,
ip=10.0.0.8, repr=MAPPOTrainer)
  File
"/home/allenwu/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py",
line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip'

**Comment by allenjeffreywu** [comment]
I've found another interesting error that I should address, I will update
you as that one gets resolved - it's probably my user error

**Comment by Theohhhu** [comment]
Have you fixed the bug yet?
