### ISSUE TITLE
How to set the number of MPE's agents?

### ISSUE THREAD

**Issue by whoisvicky** [Replicable-MARL/MARLlib#175]
I want to increase the agent numbers in the MPE environment. Is there any sample?
Also, I tried to implement IDDPG. 

`from marllib import marl

env = marl.make_env(environment_name="mpe", map_name="simple_spread", continuous_actions=True)
iddpg = marl.algos.iddpg(hyperparam_source="mpe")
model = marl.build_model(env, iddpg, {"core_arch": "mlp", "encode_layer": "128-256"})
iddpg.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 200000}, local_mode=False, num_gpus=0,
          num_workers=1, share_policy='group', checkpoint_freq=50)`

but got the error: 
RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

Can anyone help with it?

**Comment by whoisvicky** [comment]
I also tried: env = marl.make_env(environment_name="mpe", map_name="simple_spread", continuous_actions=True, 
                    env_params = {"N": 10,} )

Got ValueError                                Traceback (most recent call last)
Cell In[53], line 4
      1 from marllib import marl
      3 # prepare env
----> 4 env = marl.make_env(environment_name="mpe", map_name="simple_spread", continuous_actions=True, 
      5                     env_params = {"N": 10,} )
      7 # initialize algorithm with appointed hyper-parameters
      8 iddpg = marl.algos.iddpg(hyperparam_source="mpe")

File [~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/__init__.py:102](https://file+.vscode-resource.vscode-cdn.net/Users/vickyjwp/Desktop/code2/~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/__init__.py:102), in make_env(environment_name, map_name, force_coop, **env_params)
     99     f.close()
    101 # update function-fixed config
--> 102 env_config_dict["env_args"] = dict_update(env_config_dict["env_args"], env_params, True)
    104 # user commandline config
    105 user_env_args = {}

File [~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/common.py:50](https://file+.vscode-resource.vscode-cdn.net/Users/vickyjwp/Desktop/code2/~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/common.py:50), in dict_update(target_dict, new_dict, check)
     48 if check:
     49     if key not in target_dict:
---> 50         raise ValueError("{} illegal, not in default config".format(key))
     51     else:  # update
     52         target_dict[key] = value

ValueError: env_params illegal, not in default config

**Comment by libin-star** [comment]
hello, has this problem been solved?
