### ISSUE TITLE
Issues of create new environments

### ISSUE THREAD

**Issue by whoisvicky** [Replicable-MARL/MARLlib#176]
`from marllib import marl
from marllib.envs.base_env import ENV_REGISTRY
from ray.rllib.env.multi_agent_env import MultiAgentEnv
from gym.spaces import Dict as GymDict, Discrete, Box
import supersuit as ss
from ray.rllib.env import PettingZooEnv, ParallelPettingZooEnv
from pettingzoo.mpe import simple_tag_v2, simple_spread_v2
import time

REGISTRY = {}
REGISTRY["simple_tag_v1"] = simple_tag_v2.parallel_env(num_good=10, num_adversaries=10)
REGISTRY["simple_spread_v1"] = simple_spread_v2.parallel_env(N=20)

policy_mapping_dict = {
    "simple_tag_v1": {
        "description": "one team attack, one team survive",
        "team_prefix": ("adversary_", "agent_"),
        "all_agents_one_policy": False,
        "one_agent_one_policy": True,
    },
    "simple_spread_v1": {
        "description": "one team cooperate",
        "team_prefix": ("agent_",),
        "all_agents_one_policy": True,
        "one_agent_one_policy": True,
    },
}

class RLlibCustomMPE(MultiAgentEnv):

    def __init__(self, env_config):
        map = env_config["map_name"]
        env_config.pop("map_name", None)
        env = REGISTRY[map](**env_config)

        # keep obs and action dim same across agents
        # pad_action_space_v0 will auto mask the padding actions
        env = ss.pad_observations_v0(env)
        env = ss.pad_action_space_v0(env)

        self.env = ParallelPettingZooEnv(env)
        self.action_space = self.env.action_space
        self.observation_space = GymDict({"obs": Box(
            low=-100.0,
            high=100.0,
            shape=(self.env.observation_space.shape[0],),
            dtype=self.env.observation_space.dtype)})
        self.agents = self.env.agents
        self.num_agents = len(self.agents)
        env_config["map_name"] = map
        self.env_config = env_config

    def reset(self):
        original_obs = self.env.reset()
        obs = {}
        for i in self.agents:
            obs[i] = {"obs": original_obs[i]}
        return obs

    def step(self, action_dict):
        o, r, d, info = self.env.step(action_dict)
        rewards = {}
        obs = {}
        for key in action_dict.keys():
            rewards[key] = r[key]
            obs[key] = {
                "obs": o[key]
            }
        dones = {"__all__": d["__all__"]}
        return obs, rewards, dones, info

    def close(self):
        self.env.close()

    def render(self, mode=None):
        self.env.render()
        time.sleep(0.05)
        return True

    def get_env_info(self):
        env_info = {
            "space_obs": self.observation_space,
            "space_act": self.action_space,
            "num_agents": self.num_agents,
            "episode_limit": 25,
            "policy_mapping_info": policy_mapping_dict
        }
        return env_info

ENV_REGISTRY["custommpe"] = RLlibCustomMPE

env = marl.make_env(environment_name="custommpe", map_name="simple_spread_v1", continuous_actions=True)
print(env.get_env_info)`

I intended to create new environments. Got error:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[48], line 92
     88         return env_info
     90 ENV_REGISTRY["custommpe"] = RLlibCustomMPE
---> 92 env = marl.make_env(environment_name="custommpe", map_name="simple_spread_v1", continuous_actions=True)
     93 print(env.get_env_info)

File [~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/__init__.py:97](https://file+.vscode-resource.vscode-cdn.net/Users/vickyjwp/Desktop/code2/~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/__init__.py:97), in make_env(environment_name, map_name, force_coop, **env_params)
     93 if not os.path.exists(env_config_file_path):
     94     env_config_file_path = os.path.join(os.path.dirname(__file__),
     95                                         "../../examples/config/env_config/{}.yaml".format(environment_name))
---> 97 with open(env_config_file_path, "r") as f:
     98     env_config_dict = yaml.load(f, Loader=yaml.FullLoader)
     99     f.close()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/vickyjwp/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/../../examples/config/env_config/custommpe.yaml'

How to solve it? #175 @

>

**Comment by Miracle1207** [comment]
How to create a new env with different action spaces and observation spaces of different agents?

**Comment by whoisvicky** [comment]
> `from marllib import marl from marllib.envs.base_env import ENV_REGISTRY from ray.rllib.env.multi_agent_env import MultiAgentEnv from gym.spaces import Dict as GymDict, Discrete, Box import supersuit as ss from ray.rllib.env import PettingZooEnv, ParallelPettingZooEnv from pettingzoo.mpe import simple_tag_v2, simple_spread_v2 import time
> 
> REGISTRY = {} REGISTRY["simple_tag_v1"] = simple_tag_v2.parallel_env(num_good=10, num_adversaries=10) REGISTRY["simple_spread_v1"] = simple_spread_v2.parallel_env(N=20)
> 
> policy_mapping_dict = { "simple_tag_v1": { "description": "one team attack, one team survive", "team_prefix": ("adversary_", "agent_"), "all_agents_one_policy": False, "one_agent_one_policy": True, }, "simple_spread_v1": { "description": "one team cooperate", "team_prefix": ("agent_",), "all_agents_one_policy": True, "one_agent_one_policy": True, }, }
> 
> class RLlibCustomMPE(MultiAgentEnv):
> 
> ```
> def __init__(self, env_config):
>     map = env_config["map_name"]
>     env_config.pop("map_name", None)
>     env = REGISTRY[map](**env_config)
> 
>     # keep obs and action dim same across agents
>     # pad_action_space_v0 will auto mask the padding actions
>     env = ss.pad_observations_v0(env)
>     env = ss.pad_action_space_v0(env)
> 
>     self.env = ParallelPettingZooEnv(env)
>     self.action_space = self.env.action_space
>     self.observation_space = GymDict({"obs": Box(
>         low=-100.0,
>         high=100.0,
>         shape=(self.env.observation_space.shape[0],),
>         dtype=self.env.observation_space.dtype)})
>     self.agents = self.env.agents
>     self.num_agents = len(self.agents)
>     env_config["map_name"] = map
>     self.env_config = env_config
> 
> def reset(self):
>     original_obs = self.env.reset()
>     obs = {}
>     for i in self.agents:
>         obs[i] = {"obs": original_obs[i]}
>     return obs
> 
> def step(self, action_dict):
>     o, r, d, info = self.env.step(action_dict)
>     rewards = {}
>     obs = {}
>     for key in action_dict.keys():
>         rewards[key] = r[key]
>         obs[key] = {
>             "obs": o[key]
>         }
>     dones = {"__all__": d["__all__"]}
>     return obs, rewards, dones, info
> 
> def close(self):
>     self.env.close()
> 
> def render(self, mode=None):
>     self.env.render()
>     time.sleep(0.05)
>     return True
> 
> def get_env_info(self):
>     env_info = {
>         "space_obs": self.observation_space,
>         "space_act": self.action_space,
>         "num_agents": self.num_agents,
>         "episode_limit": 25,
>         "policy_mapping_info": policy_mapping_dict
>     }
>     return env_info
> ```
> 
> ENV_REGISTRY["custommpe"] = RLlibCustomMPE
> 
> env = marl.make_env(environment_name="custommpe", map_name="simple_spread_v1", continuous_actions=True) print(env.get_env_info)`
> 
> ## I intended to create new environments. Got error:
> FileNotFoundError Traceback (most recent call last) Cell In[48], line 92 88 return env_info 90 ENV_REGISTRY["custommpe"] = RLlibCustomMPE ---> 92 env = marl.make_env(environment_name="custommpe", map_name="simple_spread_v1", continuous_actions=True) 93 print(env.get_env_info)
> 
> File [~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/**init**.py:97](https://file+.vscode-resource.vscode-cdn.net/Users/vickyjwp/Desktop/code2/~/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/__init__.py:97), in make_env(environment_name, map_name, force_coop, **env_params) 93 if not os.path.exists(env_config_file_path): 94 env_config_file_path = os.path.join(os.path.dirname(**file**), 95 "../../examples/config/env_config/{}.yaml".format(environment_name)) ---> 97 with open(env_config_file_path, "r") as f: 98 env_config_dict = yaml.load(f, Loader=yaml.FullLoader) 99 f.close()
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/vickyjwp/opt/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/../../examples/config/env_config/custommpe.yaml'
> 
> How to solve it? #175 @

I

**Comment by whoisvicky** [comment]
accidentally closed it..... still working on how to create mpe-spread with varied agent numbers.

**Comment by whoisvicky** [comment]
I solved it. Created a new yaml file
