### ISSUE TITLE
[Question] Specify policies for the competitive 2 sides.

### ISSUE THREAD

**Issue by Yuxin916** [Replicable-MARL/MARLlib#178]
Hi, 
I am trying to train a multiagent competitive scenario with simple_tag. 3 predators 1 prey. I am wondering how to specifify policies for predator team and prey team accordingly. for example, MADDPG for predators and DDPG for prey (similar to the original MPE paper)

how should i add into the policy_mapping_fn? when exp_info["share_policy"] == "group", and len(groups) != 1.

Thank you

**Comment by Theohhhu** [comment]
By default, in MARLlib, agents should utilize the same algorithms for training. If there's a need for multiple training paradigms, I suggest referring to [RLlib's example](https://github.com/ray-project/ray/blob/ray-1.8.0/rllib/examples/two_trainer_workflow.py) and incorporating them into MARLlib by reusing the training workflow.

**Comment by Yuxin916** [comment]
Thank you for your answer. i will try to follow the example. 
Regards
