### ISSUE TITLE
customise sharing policy 

### ISSUE THREAD

**Issue by whoisvicky** [Replicable-MARL/MARLlib#180]
Following the example, I tried to customise the sharing policy for the simple spread. However, I got an error during the training.

Here is the codes for bespoke sharing policy:

policy_mapping_dict = {
    "simple_spread": {
        "description": "MPW all scenarios manually into three groups",
        "team_prefix": ("GroupA_", "GroupB_","GroupC_"),
        "all_agents_one_policy": True,
        "one_agent_one_policy": True,
    },
}

class G3_MPE(MultiAgentEnv):
    def __init__(self, map_name):
        self.env = RLlibMPE(map_name)
        self.num_agents = self.env.num_agents
        self.observation_space = self.env.observation_space
        self.action_space = self.env.action_space
        self.agents_origin = self.env.agents
        agent_ls = []
        for i in range(self.env.num_agents):
            if i < (self.num_agents // 3):
                agent_ls.append("GroupA_{}".format(i))
            elif i >= (self.num_agents // 3) and i < ((self.num_agents*2)//3) :
                agent_ls.append("GroupB_{}".format(i))
            else:
                agent_ls.append("GroupC_{}".format(i))
        self.agents = agent_ls
    
    def reset(self):
        obs_dict_origin = self.env.reset()
        obs_dict = {}
        # swap name
        for agent_origin_name, agent_name in zip(self.agents_origin, self.agents):
            obs_dict[agent_name] = obs_dict_origin[agent_origin_name]

        return obs_dict
    
    def step(self, actions):

        obs_dict_origin, reward_dict_origin, dones, info = self.env.step(actions)
        obs_dict = {}
        reward_dict = {}
        # swap name
        for agent_origin_name, agent_name in zip(self.agents_origin, self.agents):
            obs_dict[agent_name] = obs_dict_origin[agent_origin_name]
            reward_dict[agent_name] = reward_dict_origin[agent_origin_name]

        return obs_dict, reward_dict, dones, {}

    def get_env_info(self):
        return self.env.get_env_info()

I got errors: 1) [2023-08-24 08:15:37,162 E 15756 3477401] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::RolloutWorker.par_iter_next() (pid=15756, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x7f8170553460>)
  2) ray/rllib/models/preprocessors.py", line 71, in check_shape
    raise ValueError(
ValueError: ('Observation ({} dtype={}) outside given space ({})!', {'obs': array([ 0.        ,  0.        , -0.25171325, -0.0313229 , -0.33919594,
       -0.48583287, -0.27425575,  0.80054617, -0.6330307 ,  0.7672311 ,
        0.12264957,  0.8207544 ,  0.33042648,  0.8920344 , -0.469491  ,
       -0.30547124, -0.0784546 ,  0.840722  , -0.23309807, -0.70025206,
        0.2830035 , -0.34465975,  0.76312774, -0.22689265,  0.88420916,
        0.6077318 , -0.1306018 ,  0.52920014,  0.81900626,  0.07805275,
       -0.48396936,  0.5329439 ,  0.92705363,  1.0132703 ,  0.6458233 ,
       -0.9201298 ,  0.02362915,  0.72012204,  0.82006294,  0.06757133,
        0.5866221 ,  1.0269039 ,  0.78678775, -0.6515011 , -0.21052377,
       -0.7765208 ,  1.2405198 ,  0.66866595,  0.70514715,  0.21723472,
        0.18116859,  0.01790892, -0.27553913, -0.60119855,  0.3055867 ,
        0.0125381 , -0.47899485,  0.18078084,  0.24445808, -0.87987995,
        0.758898  ,  0.58498776,  0.052261  , -0.3895468 ,  1.0932549 ,
       -0.00478614,  0.36390156,  0.39977583, -0.4664369 , -0.21003309,
       -0.35961926,  0.44402036,  0.5817166 ,  1.0052768 , -0.37461284,
        0.78649807,  0.02451757, -0.18771622, -0.00891994, -0.8227166 ,
       -0.6563851 ,  0.94819564, -0.5244726 ,  0.84780234, -0.53871506,
       -0.8135378 ,  1.2328118 , -0.39304903, -0.51639557, -0.19396769,
       -0.2752163 ,  0.82471514, -0.25807288,  0.7436755 ,  1.0066743 ,
        0.46123978, -0.61460567, -0.05029437, -0.4505587 , -0.5470092 ,
        1.0868913 ,  0.27564108,  0.91982377, -0.7888157 , -0.54401076,
       -0.63982266,  0.15903267, -0.6140519 ,  0.75985944, -0.937084  ,
        0.15285781, -0.95258826,  1.0556799 , -0.5835901 ,  1.1574731 ,
       -0.51136583,  1.0314363 ,  0.2770087 ,  0.9743384 ,  0.17256473,
       -0.6878852 , -0.38474897,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.      ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ],....

Any idea why?  Thank you.

**Comment by Theohhhu** [comment]
Based on my experience, the issue arises due to the absence of proper transformation between float32 and float64 data types. Ensure that you inspect the data type of `self.observation_space` is exactly the format of the actual observation data that the environment engine returns to you within the `step` function.
