### ISSUE TITLE
Different agents load checkpoints at different times

### ISSUE THREAD

**Issue by shuo-Liu** [Replicable-MARL/MARLlib#181]
Hi!

First of all, thanks for sharing your awesome work! I have found it extremely useful.

In some competitive dyadic multi-intelligence environments, in order to evaluate the training game of both intelligences, the comparison of their capabilities at different moments is usually also analyzed, so is it possible to implement the function that each agent can choose a certain checkpoint individually, instead of all agents using the same checkpoint at the same moment, thanks!

**Comment by Theohhhu** [comment]
Hi. Thanks for your kind words.

I believe you're asking about the process of partially loading a checkpoint for a group of agents. In the context of MARLlib, it's important to note that checkpoints cannot be separated. However, you can achieve your goal by allowing certain agents to continue training and evolving while others cease (limited to inference only).

Please correct me if I've misunderstood your question.
