### ISSUE TITLE
请问MARLlib是否支持自定义任意的策略网络结构？

### ISSUE THREAD

**Issue by sdugit171** [Replicable-MARL/MARLlib#183]
MARLlib能否像类似强化学习框架Stable baselines 3那样通过继承nn.Module自定义任意的网络结构（比如GNN等），还是只能使用样例中已有的几种网络结构（MLP + CNN + GRU + LSTM）

**Comment by Theohhhu** [comment]
Thanks for your question~ 我觉得这个是RLlib的问题 如果RLlib可以定制化例如GNN+RL 那么MARLlib 也可以. 所以我建议从RLlib对模型的定制化方法寻找思路， 再应用到MARLlib中来。
