### ISSUE TITLE
Can the Env have different action and obs space?

### ISSUE THREAD

**Issue by mrz1999** [Replicable-MARL/MARLlib#185]
I'm trying to add my custom Environment to MARLlib. Is it possible to have agents with different action and observation state? And it case it's possible, how they should be specified? Because in the example provided there is only the case with same action and obs space for all the agents

**Comment by Theohhhu** [comment]
I would recommend keeping agents with the same action and observation space as the learning and inference processes of the model. This is mostly because batch-based methods prefer this approach, making things easier.

There are different ways to handle agents with different action and observation states, with the most common one being the use of the `supersuit` package as shown [here](https://github.com/Replicable-MARL/MARLlib/blob/96293a5e346c67be67ed6d40a878fc8bb8f6298b/marllib/envs/base_env/mpe.py#L103).

If possible, consider adapting your environment to use such tools to avoid this problem.

**Comment by mrz1999** [comment]
Thank you, I used the supersuit package. I try to register the Environment as in the example add_new_env.py  and I have this error: ValueError: environment "Machines" not installed properly or not registered yet, please see the Error_Log below. But the Error_Log is Null. The Environment is a ParallelEnv from the pettingzoo library (the environment is named MachineMultiAgentEnv).
This is the code I used for register the environment:

REGISTRY = {}
REGISTRY["Machines"] = MachineMultiAgentEnv

# provide detailed information of each scenario
# mostly for policy sharing
policy_mapping_dict = {
    "Machines": {
        "description": "machines cooperate for scheduling jobs",
        "team_prefix": ("M"),
        "all_agents_one_policy": True,
        "one_agent_one_policy": True,
    }
}

# must inherited from MultiAgentEnv class
class RLlibMAGym(MultiAgentEnv):

    def __init__(self, env_config):

        map = env_config["map_name"]
        env_config.pop("map_name", None)

        g = dataset_generator() # I need the dataset generator for instanziate the environment.
        env = REGISTRY[map](g) # inizialize env
        env = ss.multiagent_wrappers.pad_action_space_v0(env)
        self.env = ss.multiagent_wrappers.pad_observations_v0(env)

        self.action_space = self.env.action_spaces['M0']
        self.observation_space = GymDict({"obs": self.env.observation_spaces['M0']})
        self.agents = self.env._agent_ids
        self.num_agents = len(self.agents)
        
        env_config["map_name"] = map
        self.env_config = env_config

    def reset(self):
        original_obs = self.env.reset()
        obs = {}
        for i, name in enumerate(self.agents):
            obs[name] = {"obs": np.array(original_obs[i])}
        return obs

    def step(self, action_dict): 

        o, rewards, d, info = self.env.step(action_dict)
        obs = {}
        for key in action_dict.keys():
            
            obs[key] = {
                "obs": np.array(o[key])
            }
        dones = {"__all__": True if sum(d) == self.num_agents else False}
        return obs, rewards, dones, {}

    def close(self):
        pass

    def render(self, mode=None):
        self.env.render()
        return True

    def get_env_info(self):
        env_info = {
            "space_obs": self.observation_space,
            "space_act": self.action_space,
            "num_agents": self.num_agents,
            "episode_limit": 1000,
            "policy_mapping_info": policy_mapping_dict
        }
        return env_info


if __name__ == '__main__':
    register new env
    ENV_REGISTRY["mine"] = RLlibMAGym

I don't understand why it is not properly registered
