### ISSUE TITLE
Does MARLlib support action mask for MultiDiscrete action space?

### ISSUE THREAD

**Issue by Morphlng** [Replicable-MARL/MARLlib#187]
Hi! I noticed that MARLlib has recently added support for `MultiDiscrete` action space. However, I couldn't find any code logic that handles the action mask for this type of action space. Is it not implemented yet, or did I overlook it? If it's the latter, could you please guide me on how to form the "action_mask" in the observation, similar to `Discrete` actions?

**Comment by Morphlng** [comment]
According to this [answer](https://discuss.ray.io/t/is-any-multi-discrete-action-example-for-ppo-or-other-algorithms/4693/6) in ray forum, it seems like the action mask for `MultiDiscrete` action space is simply a flattened array of all actions. I.e.

```python
rand_env = RandomEnv(
    {
        "observation_space": Dict(
            {
                "observations": Box(-1.0, 1.0, shape=(2,)),
                "action_mask": Box(
                    0,
                    1,
                    shape=(3 * 3,),
                    dtype=int64,
                ),
            }
        ),
        "action_space": MultiDiscrete([3, 3, 3]),
    }
)
```

I've tested this kind of action_mask construction, and it worked in MARLlib.

**Comment by Jiacv** [comment]
Hello, sorry to bother you, regarding MutilDiscrete action_mask, will there be any problems in MarLlib?
`if mask_flag:
        action_mask_dim = custom_config["space_act"].n
    else:
        action_mask_dim = 0`

**Comment by Morphlng** [comment]
> Hello, sorry to bother you, regarding MutilDiscrete action_mask, will there be any problems in MarLlib? `if mask_flag: action_mask_dim = custom_config["space_act"].n else: action_mask_dim = 0`

Yes, you would have to modify the library a bit to support MultiDiscrete action mask, for example:

```python
    if mask_flag:
        action_space = custom_config["space_act"]
        if hasattr(action_space, "n"):
            action_mask_dim = action_space.n
        elif hasattr(action_space, "nvec"):
            action_mask_dim = sum(action_space.nvec)
    else:
        action_mask_dim = 0
```

You can refer to my [fork of this library](https://github.com/Morphlng/MARLlib/tree/35d3398c3eeef9d0deafb32f4d6aca9977d04e70/marllib/marl/algos/utils)
