### ISSUE TITLE
How to load the model and continue training ？

### ISSUE THREAD

**Issue by wakaka821** [Replicable-MARL/MARLlib#188]
Hello Contributor, I have trained some models with the following code.

# prepare env
env = marl.make_env(environment_name="smac", map_name="5m_vs_6m")
# initialize algorithm with appointed hyper-parameters
mappo = marl.algos.mappo(hyperparam_source="smac")
# build agent model based on env + algorithms + user preference
model = marl.build_model(env, mappo, {"core_arch": "gru", "encode_layer": "128-256"})
# start training
mappo.fit( env, model,  stop={"timesteps_total": 1000000},  checkpoint_freq=100,  share_policy="group")

Is there any way I can load the trained model and continue to train the model?
Thank you.

**Comment by Theohhhu** [comment]
Please refer to [this example](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/load_model.py). You need to maintain the identical model architecture to continue training an existing model.
