### ISSUE TITLE
Ray status shows multiple times for one iteration

### ISSUE THREAD

**Issue by Yuxin916** [Replicable-MARL/MARLlib#189]
Hi! 
Thank you for your work. 
When i am running my customized environment, which i follow the mpe and aircombat example, the training flow seems workable but for every iteration, the same event log with same reward, episode_reward
_max etc is showing multiple times. This does not happen in mpe and aircombat training. Also it keep printing out the planning time. 

Is there any way I can look into this?
Thank you.

== Status ==
Current time: 2023-09-22 20:28:44 (running for 00:15:03.20)
Memory usage on this node: 15.9/31.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 4.0/32 CPUs, 1.0/1 GPUs, 0.0/14.83 GiB heap, 0.0/7.41 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/tsaisplus/MuRPE_base/MARLlib_MuRPE/exp_results/mappo_mlp_test
Number of trials: 1/1 (1 RUNNING)
+------------------------------------------------+----------+--------------------+--------+------------------+--------+----------+----------------------+----------------------+--------------------+
| Trial name                                     | status   | loc                |   iter |   total time (s) |     ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|------------------------------------------------+----------+--------------------+--------+------------------+--------+----------+----------------------+----------------------+--------------------|
| MAPPOTrainer_test_77f04_00000 | RUNNING  | 10.2.110.232:11736 |      5 |          862.414 | 216000 |  7.66273 |                 7.68 |                7.556 |            169.635 |
+------------------------------------------------+----------+--------------------+--------+------------------+--------+----------+----------------------+----------------------+--------------------+
(RolloutWorker pid=11738) Planning time: 1.3001646995544434
(RolloutWorker pid=11739) Planning time: 1.2680127620697021
(RolloutWorker pid=11742) Planning time: 1.284132957458496
(RolloutWorker pid=11738) Planning time: 1.3487548828125
(RolloutWorker pid=11739) Planning time: 1.2872352600097656
(RolloutWorker pid=11742) Planning time: 1.3382246494293213

**Comment by Theohhhu** [comment]
The event log is generated by an internal logging reporter within `ray.tune`. The reporter is introduced into the learning pipeline at [this point](https://github.com/Replicable-MARL/MARLlib/blob/96293a5e346c67be67ed6d40a878fc8bb8f6298b/marllib/marl/algos/scripts/mappo.py#L25C1-L25C33).

The reason you're seeing the same content repeatedly is because the reporter does its job at regular intervals, regardless of whether the model has been updated or not.
