### ISSUE TITLE
Help to clarify the mappo behaviours

### ISSUE THREAD

**Issue by Coolister-Ye** [Replicable-MARL/MARLlib#192]
I'm try to use mappo to deal with mixed interaction env which has 2 two team against each other (like attacker-defender structure).  There are 4 agents in each team, who need to cooperate with their teammates. In this case, what would be a good config for the trainning to let the Centralized Critic work. 

1. When I tried to set "share_policy" to "group", the model seems to have 2 policy to work, with each policy to  deal with the all agents in the team. In this csae, is it the Centralized Critic will combine info from 2 policies or the communication just happen within the group. 
2. When i set "share_policy" to "individuals", the model would build each agent a policy. Will the CC will combine all info for each policy, or within group.

Apperciate who can give some insight about that.

**Comment by Coolister-Ye** [comment]
Let me clarify a bit more about what I am trying to achieve. I want to have idenpendent policy for each agent and the agents within a group should be able to communicate to each other to maximize the team score. The info should not be share out to another team. The game between 2 team are like a zero-sum game. I wonder the if CC is impletmented within group or not, when I set "share_policy" to "individuals".

**Comment by Theohhhu** [comment]
I understand. You need to customize the information sharing process. You can focus on [this function](https://github.com/Replicable-MARL/MARLlib/blob/96293a5e346c67be67ed6d40a878fc8bb8f6298b/marllib/marl/algos/utils/centralized_critic.py#L48), where you can build your own info-sharing strategy.

Furthermore, you can observe the behavior of different policy-sharing strategies, such as 'group' and 'individual,' in that function.

Any further questions are welcome.
