### ISSUE TITLE
Any roadmap?

### ISSUE THREAD

**Issue by Rocinate** [Replicable-MARL/MARLlib#196]
I am very happy to find this library. After rough configuration and code reading, I am surprised that the reinforcement learning related code can be encapsulated so simply and can be combined with so many algorithms and environments at the same time.
Wonder what's the direction next, any roadmap?

**Comment by Theohhhu** [comment]
Hello. You can access the roadmap [here](https://github.com/Replicable-MARL/MARLlib/blob/master/ROADMAP.md). I appreciate your acknowledgment.
