### ISSUE TITLE
Unable to install globally using setup.py

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [Replicable-MARL/MARLlib#197]
hi there,  
Thanks for the great repo, I was trying to install it, and after some fights with gym, I was able to do it.  
However, if I now use it from inside the cloned repo, it works (as `from marllib import marl` is considered a local library), but it doesn't work with global installation.

I've tried running `python setup.py install`, and it does everything correctly, but then when I try to run:
```
from marllib import marl
env = marl.make_env(environment_name="hanabi", map_name="Hanabi-Small", num_agents=3)
```
I get the following:
> CDefError: cannot parse "pyhanabi_game_t*"
> <cdef source string>:2:16: before: *

I have close to no idea what's this might even be, any idea?

Edit:  
Same happens if I go to the parent folder of the cloned repository and use `from MARLlib.marllib import marl` to import it, as soon as I run `env = marl.make_env(environment_name="hanabi", map_name="Hanabi-Small", num_agents=3)` it gives that error

**Comment by Theohhhu** [comment]
Hi. The issue might be related to the installation method of Hanabi and its organization within MARLlib. Using it inside the cloned repository should work fine. If you want to use it globally, it might be necessary to treat Hanabi as an additional dependency, similar to how PettingZoo and SMAC are handled.
