### ISSUE TITLE
Does this framework support asynchronous execution of the step function for different agents?

### ISSUE THREAD

**Issue by JSA-458** [Replicable-MARL/MARLlib#198]
Hi!Does this framework support asynchronous execution of the step function for different agents?

**Comment by Theohhhu** [comment]
Yes, there are existing examples in MARLlib such as Hanabi or a modified version of MPE. You can experiment with modifying [this line](https://github.com/Replicable-MARL/MARLlib/blob/0d73a4302fffa7a4584bafd0875ca996f636c1ad/marllib/envs/base_env/mpe.py#L33) to `REGISTRY["simple_adversary"] = simple_adversary_v2.env` and configure the environment using `self.env = PettingZooEnv(env)` to enable asynchronous execution for MPE.
