### ISSUE TITLE
Evaluating agents after training

### ISSUE THREAD

**Issue by Nafisanaznin** [Replicable-MARL/MARLlib#209]
I want to evaluate the trained agent. Is there any API or method that helps me to run already trained agents?

**Comment by Maxwell-R** [comment]
Please see [MARLlib](https://github.com/Replicable-MARL/MARLlib/tree/master)/[examples](https://github.com/Replicable-MARL/MARLlib/tree/master/examples)
/load_and_render_model.py for more information

**Comment by Theohhhu** [comment]
Thanks to @Maxwell-R for providing the guidance!
