### ISSUE TITLE
Continue my Training process

### ISSUE THREAD

**Issue by DuangZhu** [Replicable-MARL/MARLlib#210]
hi, how can i Continue my Training process, while it stop. I try add the 'restore_path', but it didn't continue training but test.

**Comment by Aequatio-Space** [comment]
in `run_cc.py` you can see that restore_path is being linked to testing. 
https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/marllib/marl/algos/run_cc.py#L34-L48
To restore training progress, perhaps try resume=True in the ray.init? Or you can also rewrite the relevant logic to circumvent this issue.
