### ISSUE TITLE
Where is numpy.object_ from?

### ISSUE THREAD

**Issue by fulacse** [Replicable-MARL/MARLlib#211]
from marllib import marl

env = marl.make_env(environment_name="sisl", map_name="pursuit")

mappo = marl.algos.mappo(hyperparam_source="common")

model = marl.build_model(env, mappo, {
    "conv_layer": 3,
    "out_channel_layer_0": 64,
    "kernel_size_layer_0": 3,
    "stride_layer_0": 1,
    "padding_layer_0": 0,
    "pool_size_layer_0": 1,
    "out_channel_layer_1": 128,
    "kernel_size_layer_1": 3,
    "stride_layer_1": 1,
    "padding_layer_1": 0,
    "pool_size_layer_1": 1,
    "out_channel_layer_2": 256,
    "kernel_size_layer_2": 3,
    "stride_layer_2": 1,
    "padding_layer_2": 0,
    "pool_size_layer_2": 1,
    "hidden_state_size": 512,
    "core_arch": "mlp",
})

mappo.fit(env, model, stop={'timesteps_total': 1000000}, share_policy='all', checkpoint_freq=10, checkpoint_end=True,
          local_mode=False, num_gpus=1, num_workers=5)
[error.txt](https://github.com/Replicable-MARL/MARLlib/files/13799156/error.txt)

**Comment by fulacse** [comment]
and I don't want pool layer, how do I remove it?

**Comment by Aequatio-Space** [comment]
For the "numpy.object_" problem, try checking https://github.com/ray-project/ray/pull/26863, you may find the solution in commits.
Apply a patch to the ray library will solve the problem.

Pooling layer is hardcoded in here, if you want to get rid out of it, some modification of the library may needed.
https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/marllib/marl/models/zoo/encoder/base_encoder.py#L79-L80

**Comment by fulacse** [comment]
> For the "numpy.object_" problem, try checking [ray-project/ray#26863](https://github.com/ray-project/ray/pull/26863), you may find the solution in commits. Apply a patch to the ray library will solve the problem.
> 
> Pooling layer is hardcoded in here, if you want to get rid out of it, some modification of the library may needed.
> 
> https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/marllib/marl/models/zoo/encoder/base_encoder.py#L79-L80

Thanks, is probleme of pythorch version. And I think it don't change anything if pool_size = 1
