### ISSUE TITLE
Access Value Function After algo.Fit

### ISSUE THREAD

**Issue by thomasychen** [Replicable-MARL/MARLlib#216]
We are using marllib to train IPPO multiagent environment and we want to access the value functions of each agent after an iteration of calling ippo.fit() to do some additional analysis.

We've seen that the model tuple is just a class type and the config dictionary, is there any way to access the instantiation of the model class itself, to access the attributes of (eg. BaseMLP) like value_function(). If not, is there a way to instantiate our own BaseMLP class or some other policy class and load in the weights from a checkpoint, specifically the same file that is used in render() as "model_path"?

**Comment by Aequatio-Space** [comment]
You can try to override the `extra_action_out_fn` of IPPOTorchPolicy, using code like:
```
IPPOTorchPolicy = PPOTorchPolicy.with_updates(
    name="IPPOTorchPolicy",
    get_default_config=lambda: PPO_CONFIG,
    extra_action_out_fn=extra_action_out_fn
)
```

In ray, you can see that PPOTorchPolicy is constructed similarly:
https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/agents/ppo/ppo_torch_policy.py#L258-L273

and a custom `extra_action_out_fn` is named `vf_pred_fetches`:
https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/agents/ppo/ppo_torch_policy.py#L150-L176

which gives you the access to model instance.

**Comment by thomasychen** [comment]
Thanks, this worked out
