### ISSUE TITLE
How MARLlib works with ray algorithms like PPO?

### ISSUE THREAD

**Issue by SaraRezaei** [Replicable-MARL/MARLlib#220]
said MARLlib supports 18 algorithms but just there is examples with MA-algorithms not ray algorithms like PPO,A2C,A3C and ...

with those lines:
    algo = marl.algos.ppo(hyperparam_source="test")
    # customize model
    model = marl.build_model(env, algo, {"core_arch": "mlp", "encode_layer": "128-128"})
    # start learning
    algo.fit(env, model, stop={'episode_reward_mean': 4.0, 'timesteps_total': 1000000000 }, local_mode=True, num_gpus=0,  
      num_workers=2, share_policy='all', checkpoint_freq=50)

I got this error:
    algo = marl.algos.ppo(hyperparam_source="test")
AttributeError: '_AlgoManager' object has no attribute 'ppo'

**Comment by Aequatio-Space** [comment]
MARLlib does not support "ppo", it supports multi-agent versions of them like mappo, ippo, vdppo, happo.

**Comment by SaraRezaei** [comment]
Thanks, but what is the 18 algorithms which MARLlib support them?

![Screenshot 2024-02-09 112137](https://github.com/Replicable-MARL/MARLlib/assets/104292797/4b41717b-ac6d-4dbf-b4d8-5b0ba3e3dabb)
