### ISSUE TITLE
Is it a hard-fork of the Ray Repo?

### ISSUE THREAD

**Issue by mickelliu** [Replicable-MARL/MARLlib#38]
Any plan to update the base Ray version in the future?

**Comment by Theohhhu** [comment]
Currently no.
Different Ray versions got different APIs and changing the base Ray version (for MARLlib is 1.8.0) causes bugs.

**Comment by GoingMyWay** [comment]
> Currently no. Different Ray versions got different APIs and changing the base Ray version (for MARLlib is 1.8.0) causes bugs.

@Theohhhu, can you tell me more about potential bugs? I want to use it with ray 1.11.
