### ISSUE TITLE
Integrating with VMAS vectorized simulator

### ISSUE THREAD

**Issue by matteobettini** [Replicable-MARL/MARLlib#52]
Hello,

In my lab we have created a MARL simulator and benchmarking platform called VMAS:
[https://github.com/proroklab/VectorizedMultiAgentSimulator](https://github.com/proroklab/VectorizedMultiAgentSimulator).

It is a vectorized simulator using pytorch which contains all the Multiagent Particle Environments scenarios and an additional set of 12 multi-robot scenarios.

Have a look at the repo, it would be nice to make our environments available in your project and it should be pretty easy since we support the RLLib VectorEnv interface.

**Comment by Theohhhu** [comment]
Hi Matt,

Incorporating more multi-agent environments will be our primary task in future development.
Thanks for your suggestion.

Siyi
