### ISSUE TITLE
how to render trained model

### ISSUE THREAD

**Issue by hyoonsoo** [Replicable-MARL/MARLlib#55]
Hello.
Trained result confirmed that the log was saved.
Can I render trained model using this log?
How can I do that?
(I want to recall the saved results and reproduce them.)

**Comment by Theohhhu** [comment]
Hi, 
Currently, we do not have a unified rendering interface. 
You can modify the environment and render the saved model as you like.
For how to evaluate and render in RLlib, please refer to:
https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/examples/env_rendering_and_recording.py
