### ISSUE TITLE
Documentation about the hyperparameters

### ISSUE THREAD

**Issue by JackYansongLi** [Replicable-MARL/MARLlib#61]
One comments shown in marl/algos/hyperparams/finetuned/mpe/maddpg.yaml suggests
```console
# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/ddpg/ddpg.py
```
However, it looks like ray just updated their documentations. There are no detailed explanations in ray/rllib/agents/ddpg/ddpg.py.

**Comment by Theohhhu** [comment]
The old doc is not available anymore. If you wanna  look at it, try build one: https://github.com/ray-project/ray/tree/ray-1.8.0/doc

**Comment by Theohhhu** [comment]
You are welcome to reopen the issue if you have further concerns.
