### ISSUE TITLE
Heterogeneous policy?

### ISSUE THREAD

**Issue by JackYansongLi** [Replicable-MARL/MARLlib#62]
Can the configuration files be changed to make each agent uses different algorithms during training? For example, one agent uses the IPPO algorithm while another agent uses IQL algorithm.

**Comment by Theohhhu** [comment]
Yes.
RLlib provides an example [here](https://github.com/ray-project/ray/blob/ray-1.8.0/rllib/examples/two_trainer_workflow.py).

**Comment by JackYansongLi** [comment]
Is it possible to replicate the example you provide by simply altering the .yaml files you provide in this package?
