### ISSUE TITLE
Trial Pending

### ISSUE THREAD

**Issue by JackYansongLi** [Replicable-MARL/MARLlib#63]
I am trying to run MADDPG in mpe(with simple_adversary). However, the algorithm stucks with a log shows the trial is pending.

I saw a similar issue here: https://github.com/ray-project/ray/issues/16425. It says that this is due to the resource allocation.

I am using a 16 core cpu and a GTX 1650s gpu. So I tried to set ray.yaml file as follows:

num_workers: 2
num_gpus: 1
num_cpus_per_worker: 8
num_gpus_per_worker: 0.5

I also tried several different options such as:

num_workers: 2
num_gpus: 1
num_cpus_per_worker: 1
num_gpus_per_worker: 0.3

However, no matter how I alter the setting. The algorithm still stucks with trial pending.

**Comment by Theohhhu** [comment]
set num_gpus_per_worker = 0 to see if it works.
In most cases, samplers(workers) do not need GPU.

**Comment by Theohhhu** [comment]
Is there any bug reported before the trmination?

**Comment by JackYansongLi** [comment]
The issue is caused by the version of petting zoo. The API used in MARLlib does not consist with the current version of pettingzoo. Use the following command solves the problem.
```console
pip install pettingzoo[mpe]==1.12.0
```
