### ISSUE TITLE
VMAS integration

### ISSUE THREAD

**Issue by matteobettini** [Replicable-MARL/MARLlib#64]
Hello,

We have recently developed a vectorised version of MPE with more environments and robotics scenarios.

[https://github.com/proroklab/VectorizedMultiAgentSimulator](https://github.com/proroklab/VectorizedMultiAgentSimulator)

It is by default compatible with the VectorEnv RLLib interface. 
Would this work straight away in your framework? Are you interested in adding it to the list of supported envs? 

Have a look at the project and let me know.

Best,

Matteo

**Comment by Theohhhu** [comment]
Sure, currently our paper is under review therefore the integration of algorithms needs to be stable.
