### ISSUE TITLE
PettingZoo version and missing dependence.

### ISSUE THREAD

**Issue by JackYansongLi** [Replicable-MARL/MARLlib#67]
To replicate the result of your work in the MPE environment, the following packages should be installed (and are not mentioned in your documentation)
```console
pip install gym==0.21.0
pip install pettingzoo==1.21.0
pip install supersuit ==3.3.0
pip install icecream
```

**Comment by Theohhhu** [comment]
Right. Thanks for your correction. We will have a major revision to our instructions.  Issues will be fixed and add new functions will be added.

**Comment by Yuxin916** [comment]
> To replicate the result of your work in the MPE environment, the following packages should be installed (and are not mentioned in your documentation)
> 
> ```
> pip install gym==0.21.0
> pip install pettingzoo==1.21.0
> pip install supersuit ==3.3.0
> pip install icecream
> ```

Thank you so much! May i ask what's your Pytorch version? Thanks!
