### ISSUE TITLE
Regarding inferencing the learnt policy 

### ISSUE THREAD

**Issue by SiddSS** [Replicable-MARL/MARLlib#69]
Hi,
We have created our custom environment for and wrapped it in a gym class. After training using MAPPO, we got the .pkl files. Can you elaborate upon how to inference the learned policy ?
We already have a visualization of the env using pygame and just want to load the learned policies and see them play.

Thanks in advance.

**Comment by Theohhhu** [comment]
It is doable. However, MARLlib decides not to incorporate the loading and rendering functions as we find it hard to unify all ten environments to render in a similar pattern.

**Comment by SiddSS** [comment]
Hi Thanks for the previous answer. But we have been unable to use the learned policy to compute actions for our agents. Our objective is to compute agent's actions based on the learnt policy. But when we use the function agent.compute_single_action(obs), where obs = env.reset()
We get the error that seq_lens in None type. We are not able to find where to find the sequence lengths to resolve this error. We added some print statements in the training and could observe the sequence lengths being printed there but compute_single_action does not seem to be workking with that. 

It would be really helpful if you could provide some insights for the same. Also kindly let us know if we should be using some function other than agent.compute_single_action for the same purpose.

**Comment by Theohhhu** [comment]
Hi SiddSS,

Sorry for the late reply. Please check [this example](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/marl/render/example.py) for loading the checkpoint and rendering the environment in MARLlib. 
You are welcomed for any further question.

Siyi

**Comment by Theohhhu** [comment]
New APIs are [here](https://github.com/Replicable-MARL/MARLlib/tree/sy_dev/examples) for guiding how to render the pretrained model.
