### ISSUE TITLE
Great work! Is this compatible with latest RLLib?

### ISSUE THREAD

**Issue by pengzhenghao** [Replicable-MARL/MARLlib#80]
Great job! I like this comprehensive benchmark

I just developed [CoPO, a MARL algorithm explicitly modeling the coordination between self-interested agents](https://decisionforce.github.io/CoPO/), based on latest RLLib ray=2.2.0. If this repo is compatible I would like to contribute my code to enrich this project.

**Comment by Theohhhu** [comment]
It is not. MARLlib is based on ray=1.8.0. No forward and backward compatibility
