### ISSUE TITLE
What version of MAgent is compatible with MARLlib?

### ISSUE THREAD

**Issue by Morphlng** [Replicable-MARL/MARLlib#81]
According to the doc about [Environments](https://marllib.readthedocs.io/en/latest/handbook/env.html#magent), it would be fine to just use `pip install pettingzoo[magent]`. However, the latest version of [pettingzoo](https://github.com/Farama-Foundation/PettingZoo/tree/master/pettingzoo/magent) has moved MAgent to a dedicated project, so its unusable now.

I've compared the code in `envs/base_env/magent.py` with pettingzoo's previous version.

https://github.com/Replicable-MARL/MARLlib/blob/e1ddcef519b5d6736f140bcf8ad75689de62bff7/envs/base_env/magent.py#L5-L14

It seems like we have to use version before 1.15.0 (e.g. 1.14.0). Yet, after `pip install pettingzoo[magent]==1.14.0` and run a test, it reports problem as: "cannot import name 'aec_to_parallel' from 'pettingzoo.utils.conversions'"

I've tried newer version of MAgent and changed magent.py accordingly, but it will raise other problems.

So which version has been tested exactly?

**Comment by Morphlng** [comment]
Okay I've found a solution. The following version works for me `pip install supersuit==3.3.2 pettingzoo[magent]==1.14.0`. Higher version of pettingzoo doesn't match the supersuit check.

I think the document/readme need an update.

**Comment by Theohhhu** [comment]
A [requirements.txt](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/requirements.txt) is here for you to refer. Yet there is no need to strictly follow it. 

The document/readme will be updated.
