### ISSUE TITLE
Question about the patches

### ISSUE THREAD

**Issue by XiAoSSuper** [Replicable-MARL/MARLlib#83]
Hi, I'm working on this wonderful repo.
May I have your attention?
I am new to RLlib as well as MARLlib. I want to know why and how to use the 'patches'. 
As shown in the pictures below.
![Image](https://user-images.githubusercontent.com/45323687/221754852-7203c154-4516-4752-b51d-4d3c9a815148.png)
![Image](https://user-images.githubusercontent.com/45323687/221754861-e67bf091-9099-421c-8fdc-a1c69bffc908.png)
Thanks for your help!

**Comment by Theohhhu** [comment]
So far MARLlib is only available on Linux.

**Comment by XiAoSSuper** [comment]
Alright, thx a lot
