### ISSUE TITLE
Trained baseline models missing + some results missing?

### ISSUE THREAD

**Issue by Arosseau** [Replicable-MARL/MARLlib#84]
Would it possible to provide the trained models (weights) as well?

Moreover, when looking at the results, I could not find the results for the MAgent Gather game, though it is mentioned in the docs and in the MAgent env file.

**Comment by Theohhhu** [comment]
Please have a look at our [new api  design](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/examples/train_example.py) and how to load a trained model and render the policy [here](https://github.com/Replicable-MARL/MARLlib/tree/sy_dev/examples/render_policy). The accompanied doc is on the way.

**Comment by Arosseau** [comment]
Both links give a 404 error (non-public?). Moreover, the question about the MAgent Gather environment results is not answered?

**Comment by Theohhhu** [comment]
Links should be ok now. As for magent, we only conduct experiments on four mixed(cooperative-competitive) scenarios. Currently, there is no pretrained model provided.
