### ISSUE TITLE
Regarding using trained policies

### ISSUE THREAD

**Issue by david-man** [Replicable-MARL/MARLlib#86]
Hello,

We have created our custom environment for and wrapped it in a gym class. After training using MAPPO, we got checkpoint files including params and .pkl files. 

We want to now use the trained policy to evaluate certain observation spaces that we feed the policy. How should we go about this?

**Comment by david-man** [comment]
For clarification, I'm not looking to simply render the model. I'm looking to load and input into the model.

**Comment by Theohhhu** [comment]
Would it be possible for you to provide an example, such as a pseudo code, that illustrates what you're looking for?

**Comment by david-man** [comment]
Given RLLib's codebase, it likely would look somewhat similar to the below.

example_env = Env(env_config = {})
trainer = MAPPOTrainer(config = config, env = Env)
obs = example_env.reset()
trainer.restore(checkpoint_path = checkpoint_path)
policy = trainer.get_policy(agent_name)
actions = trainer.compute_actions(obs = obs, policy = policy) //actions would be in the form of a dictionary, one for each agent

**Comment by Theohhhu** [comment]
At the moment, we only offer automated training with Ray[tune] and do not support manual training with a training loop. However, I do believe that manual training is crucial, as seen in other RL and MARL libraries. Please be patient as we continue to develop our codebase to implement this feature.

**Comment by david-man** [comment]
Sorry if I did not phrase my question correctly. After running the automated training module with Ray[tune], we get a checkpoint path + parameters. I was trying to see if there was a way to use the policy stored in this checkpoint to make inferences about an inputted observation.

**Comment by Theohhhu** [comment]
Will integrate this feature in the future version. Please check out [here](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/ROADMAP.md) for the future roadmap.
