### ISSUE TITLE
Documentation outdated and installation irreproducible

### ISSUE THREAD

**Issue by Arosseau** [Replicable-MARL/MARLlib#87]
There is large mismatch between the Readme and the docs. The docs seem to be for an older version of the project? E.g., the example training script from the docs does not work anymore (I believe it has been replaced by the main.py file so that the code can be run from the terminal?).

Also, what version of PettingZoo are you using? I am trying to run the MAgent examples, but by now there is an MAgent2 library which has taken over the PettingZoo[magent] repo. I have tried to find the older version of PettingZoo that matches your code to run the main.py file, but I cannot find it, and I keep getting errors because of this. Can you provide it, please, and also update your docs/readme asap? This is important for the long-term health of your project.

Thank you.

**Comment by david-man** [comment]
Did you pull from the sy_dev branch? That branch is the most updated one that matches with the docs; the main branch itself is not updated.

**Comment by Theohhhu** [comment]
Hello guys, apologize for any confusion. The document is currently based on the sy_dev branch and we plan to merge it into the dev branch once we finalize the new version of MARLlib.
