### ISSUE TITLE
TuneError

### ISSUE THREAD

**Issue by abdulghani91** [Replicable-MARL/MARLlib#88]
whene I run the code belwo:

python3 marl/main.py --algo_config=qmix [--finetuned] --env_config=smac with env_args.map_name=3m

I got this error:

(pid=341594) [2023-03-20 15:46:49,756 E 341594 341920] raylet_client.cc:159: IOError: Broken pipe [RayletClient] Failed to disconnect from raylet.
Traceback (most recent call last):
  File "marl/main.py", line 53, in <module>
    run_vd(config_dict)
  File "/media/user/APPS/AI Safety/MultiAgents RL/Algorithms/MARLlib/marl/algos/run_vd.py", line 218, in run_vd
    results = POlICY_REGISTRY[config_dict["algorithm"]](config_dict, common_config, env_info_dict, stop)
  File "/media/user/APPS/AI Safety/MultiAgents RL/Algorithms/MARLlib/marl/algos/scripts/vdn_qmix_iql.py", line 78, in run_joint_q
    results = tune.run(Trainer,
  File "/home/user/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py", line 624, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [QMIX_grouped_smac_3m_43fcd_00000])
(pid=341594) CloseHandler: 127.0.0.1:51406 disconnected

could any one help me with that?

im using 
ubuntu: 20.04
python: 3.8.16 (conda)
torch:  1.13.1+cu117
ray: 1.8.0

**Comment by Theohhhu** [comment]
Please set `local_mode = True` and include the full stack trace of the error so that we can investigate it thoroughly.

**Comment by abdulghani91** [comment]
@Theohhhu Thank you its work now. I downgrade numpy from 1.24 to 1.23.1 and set the local_mode = True.

did I have to turn the GPU usage on, because the usage of the GPU is 0.0

`Resources requested: 1.0/16 CPUs, 0/1 GPUs, 0.0/15.06 GiB heap, 0.0/7.53 GiB objects (0.0/1.0 accelerator_type:G)`

**Comment by Theohhhu** [comment]
When `local_mode=True`, the GPU usage is turned off by default, regardless of the number of GPUs you have.

**Comment by abdulghani91** [comment]
@Theohhhu I set the `local_mode=False`, and set the `num_gpus_per_worker: 1`, but the usage of GPU still 0.0

`esources requested: 1.0/16 CPUs, 0/1 GPUs, 0.0/15.32 GiB heap, 0.0/7.66 GiB objects (0.0/1.0 accelerator_type:G)`

**Comment by Theohhhu** [comment]
I could help, but I suggest you check out our [new APIs](https://github.com/Replicable-MARL/MARLlib/tree/sy_dev), and based on that, if the bug persists, feel free to create an issue and I will be happy to help you out.

**Comment by abdulghani91** [comment]
@Theohhhu Thanks this will helped me alot
