### ISSUE TITLE
Hyperparameters in sy_dev vs main branch

### ISSUE THREAD

**Issue by Arosseau** [Replicable-MARL/MARLlib#89]
Hi,

It seems a lot of the finetuned hyperparameters from the main branch are missing in the sy_dev branch. Are the hyperparameters from the main branch still valid in the new sy_dev branch as well?

Thank you.

**Comment by Theohhhu** [comment]
We delete them because we have found no significant difference in performance on these tasks/environments when fine-tuning these hyperparameters. We recommend that you use commonly used hyperparameters and fine-tune them yourself.

**Comment by Arosseau** [comment]
Thanks. Are the hyperparameter search grids somewhere available for all agents that were used, to know how much more finegrained I need to go than your search?

**Comment by Theohhhu** [comment]
Currently no.
