### ISSUE TITLE
ValueError: illegal action space

### ISSUE THREAD

**Issue by issuey** [Replicable-MARL/MARLlib#90]
When I use qmix to the mpe environment like this
python marl/main.py --algo_config=qmix --env_config=mpe with env_args.map_name=simple_spread

it will produce a problem below
**ValueError: illegal action space**

I checked the value of space_act, the value of it is Discrete(5), it is the instance of Discrete, but the result of isinstance(space_act, Discrete) is False.

Why does this create such a problem?Looking for your help.

**Comment by Theohhhu** [comment]
Hi, please check out our [new API](https://github.com/Replicable-MARL/MARLlib/tree/sy_dev) and see whether the bug still exists.

**Comment by issuey** [comment]
Now the problem doesn't exist, but I met another problem, how can I make the mpe enviornment visible to check the result?

**Comment by Theohhhu** [comment]
You can refer to [this example](https://github.com/Replicable-MARL/MARLlib/blob/sy_dev/examples/load_and_render_model.py).
