### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by Morphlng** [Replicable-MARL/MARLlib#92]
Hi! I'm glad to see the latest upgrade of MARLlib with update to date document. But I'm a bit confused about the relationship of these Api-based usage with previous console-based usage. So, I want to make sure something:

1. I don't see the `main.py` anymore, does this mean that the console-based usage is completely deprecated?
2. Besides the change of usage, is there any algorithm related improvement? (Is there a detailed version info?)
3. What is the relationship between previously required 4 config file and the new Api? Also, it seems like there are some new configurations, for example:

```python
# build agent model based on env + algorithms + user preference
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

# start training
mappo.fit(env, model, stop={"timesteps_total": 1000000}, checkpoint_freq=100, share_policy="group")
```

Is there a full document of what exactly can be configured? Or should I just refer to Ray's document?

**Comment by Theohhhu** [comment]
please refer to the [version info](https://github.com/Replicable-MARL/MARLlib/releases/tag/1.0.2) and the [doc related part](https://marllib.readthedocs.io/en/latest/handbook/quick_start.html#how-to-customize).
