### ISSUE TITLE
From progress.csv to result.csv

### ISSUE THREAD

**Issue by Luma41** [Replicable-MARL/MARLlib#94]
Hello,
maybe I've read over this/its basic knowledge but while looking at your example results I noticed how different the csv looks. 
If I did understand correctly (and my small training worked) I "only" get a progress.csv and a result.json and the progress.csv has a lot of information which is really hard to read. I wanted to ask how did you manage to do that? What data did you take out of the progress.csv?

Thank you and sorry if its a inconvenient

**Comment by Theohhhu** [comment]
All the learning curves are obtained from the regular tfevents within the logging folder. If you're unable to locate the logging directory, kindly inform me so that I can assist you further.

**Comment by Luma41** [comment]
Hi thank you for your answer,
Do you mean with logging folder the output file from the training or rendering? I have a tfevents there but I can't open it. 
Is the data for the tfevents from the result.json?

I want to train with a CNN due to seeing it on your List of Models  but only saw that you have something called a cnn_encoder. I tried to find something but I didn't find anything on what it exactly is or how to access it. Or does the Base_encoder always takes the cnn_encoder and at the end the fc_encoder? Or would i need to implement one myself?

Is ITRPO or IPPO automatically an actor-critic and A2C is an advanced version of an actor-critic?

**Comment by Theohhhu** [comment]
To open tfevents files, you have to: 

- Install TensorFlow: To open TFEvents files, you need to have TensorFlow installed on your system. You can install TensorFlow using pip or conda package manager.
- Install TensorBoard: TensorBoard is a visualization tool for TensorFlow that can be used to open and visualize TFEvents files. You can install it using pip or conda package manager.
- Launch TensorBoard: Once you have installed TensorBoard, launch it using the following command in your terminal or command prompt: `tensorboard --logdir=path/to/logs`
- Open the TensorBoard UI: Open your web browser and go to localhost:6006 to access the TensorBoard UI. You should see a dashboard with various tabs for different types of visualizations.
- Load your TFEvents file: Click on the "Load data" button and select the TFEvents file you want to open. You can then navigate through the various tabs to visualize the training process and metrics.

**Comment by Theohhhu** [comment]
Regarding the choice between CNN or MLP, it is typically determined by the nature of the observation space and is often selected automatically. As for your comment on the reinforcement learning algorithms, you are correct that TRPO and PPO are examples of actor-critic algorithms, while A2C is an advanced version of the actor-critic approach.

**Comment by Luma41** [comment]
Hi thank you for your answer. I managed to make it work, but while looking at the graph new questions arose. I tried to find out if my model overfit or not but all the information from tensorflow on the internet had other names/values than what I can see on the outputfile from your training. 
Where did you configure what to let tensorflow plot?
Do you know which values show me the overfitting?
